<?php
$page_title='สมุดที่อยู่';require_once __DIR__.'/includes/auth_check.php';requireLogin();require_once __DIR__.'/config/database.php';$db=(new Database())->getConnection();$stmt=$db->prepare('SELECT * FROM user_addresses WHERE user_id=? ORDER BY is_default DESC,id DESC');$stmt->execute([(int)$_SESSION['user_id']]);$addresses=$stmt->fetchAll();require __DIR__.'/includes/header.php';
?><div class="container" id="addressBook" style="margin:36px auto 70px;max-width:980px"><div class="section-header"><div><p class="eyebrow">DELIVERY ADDRESS</p><h1>สมุดที่อยู่</h1><p>บันทึกหลายที่อยู่และเลือกใช้ตอนชำระเงิน</p></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:22px"><section class="checkout-card"><h2>เพิ่มที่อยู่ใหม่</h2><form id="addressForm"><label>ชื่อเรียก<input name="label" maxlength="50" value="บ้าน" required></label><label>ชื่อผู้รับ<input name="recipient_name" maxlength="100" value="<?php echo e($_SESSION['full_name']??'');?>" required></label><label>เบอร์โทร<input name="phone" inputmode="tel" maxlength="20" required></label><label>ที่อยู่<textarea name="address_line" data-address-picker required rows="4"></textarea></label><input type="hidden" name="action" value="save"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><button class="btn btn-primary">บันทึกที่อยู่</button></form></section><section style="display:grid;gap:12px;align-content:start"><?php if(!$addresses):?><div class="checkout-card">ยังไม่มีที่อยู่ที่บันทึกไว้</div><?php endif;?><?php foreach($addresses as $a):?><article class="checkout-card"><div style="display:flex;justify-content:space-between"><strong><?php echo e($a['label']);?><?php echo $a['is_default']?' · ค่าเริ่มต้น':'';?></strong><span><?php echo e($a['recipient_name']);?></span></div><p><?php echo e($a['address_line']);?><br><?php echo e($a['phone']);?></p><div style="display:flex;gap:8px"><?php if(!$a['is_default']):?><button class="btn btn-outline" onclick="addressAction(this,'default',<?php echo (int)$a['id'];?>)">ตั้งเป็นค่าเริ่มต้น</button><?php endif;?><button class="btn btn-danger" onclick="addressAction(this,'delete',<?php echo (int)$a['id'];?>)">ลบ</button></div></article><?php endforeach;?></section></div></div>
<script nonce="<?php echo e(cspNonce());?>">
async function refreshAddressBook(){const response=await fetch(location.href);if(!response.ok)throw new Error('โหลดสมุดที่อยู่ล่าสุดไม่สำเร็จ');const doc=new DOMParser().parseFromString(await response.text(),'text/html'),fresh=doc.getElementById('addressBook'),current=document.getElementById('addressBook');if(!fresh||!current)throw new Error('ไม่พบข้อมูลสมุดที่อยู่');current.replaceWith(fresh);if(typeof initThaiAddressPickers==='function')initThaiAddressPickers();bindAddressForm()}
function bindAddressForm(){const form=document.getElementById('addressForm');if(!form)return;form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const response=await fetch(`${BASE_URL}api/addresses.php`,{method:'POST',body:new FormData(form)}),result=await response.json();if(!response.ok||result.status!=='success')throw new Error(result.message||'บันทึกไม่สำเร็จ');await refreshAddressBook();showToast(result.message,'success')}catch(error){button.disabled=false;showToast(error.message,'error')}}}
async function addressAction(button,action,id){if(action==='delete'&&!confirm('ลบที่อยู่นี้?'))return;button.disabled=true;const data=new FormData();data.append('action',action);data.append('id',id);data.append('csrf_token',CSRF_TOKEN);try{const response=await fetch(`${BASE_URL}api/addresses.php`,{method:'POST',body:data}),result=await response.json();if(!response.ok||result.status!=='success')throw new Error(result.message||'ดำเนินการไม่สำเร็จ');await refreshAddressBook();showToast(result.message,'success')}catch(error){button.disabled=false;showToast(error.message,'error')}}
document.addEventListener('DOMContentLoaded',bindAddressForm);
</script><?php require __DIR__.'/includes/footer.php';?>
