<?php
$page_title='รายละเอียดคำสั่งซื้อ';$noindex=true;require_once __DIR__.'/includes/auth_check.php';requireLogin();require_once __DIR__.'/config/database.php';
$db=(new Database())->getConnection();$id=(int)($_GET['id']??0);$order=null;$items=[];$history=[];$fulfillments=[];
if($db&&$id>0){$s=$db->prepare('SELECT * FROM orders WHERE id=? AND user_id=? LIMIT 1');$s->execute([$id,(int)$_SESSION['user_id']]);$order=$s->fetch();if($order){$s=$db->prepare("SELECT oi.*,p.image_url,COALESCE(sp.shop_name,'KitchenMate Mall') shop_name FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id LEFT JOIN seller_profiles sp ON sp.user_id=oi.seller_id WHERE oi.order_id=? ORDER BY COALESCE(oi.seller_id,0),oi.id");$s->execute([$id]);$items=$s->fetchAll();try{$s=$db->prepare('SELECT * FROM order_status_history WHERE order_id=? ORDER BY created_at DESC,id DESC');$s->execute([$id]);$history=$s->fetchAll();$s=$db->prepare('SELECT * FROM order_fulfillments WHERE order_id=? ORDER BY updated_at DESC,id DESC');$s->execute([$id]);$fulfillments=$s->fetchAll();}catch(Throwable $ignored){}}}
if(!$order){header('Location: '.BASE_URL.'my-orders.php');exit;}
$statusLabels=['pending'=>'รับคำสั่งซื้อแล้ว','processing'=>'กำลังจัดเตรียมสินค้า','shipped'=>'พัสดุอยู่ระหว่างการจัดส่ง','completed'=>'พัสดุถูกจัดส่งสำเร็จแล้ว','cancelled'=>'คำสั่งซื้อถูกยกเลิก'];
$fulfillmentLabels=['pending'=>'ร้านค้าได้รับคำสั่งซื้อแล้ว','accepted'=>'ร้านค้ากำลังเตรียมสินค้า','packing'=>'กำลังแพ็กสินค้า','shipped'=>'พัสดุอยู่ระหว่างการจัดส่ง','delivered'=>'พัสดุถูกจัดส่งสำเร็จแล้ว','cancelled'=>'ยกเลิกการจัดส่ง'];
$paymentLabels=['promptpay'=>'พร้อมเพย์ QR','cod'=>'เก็บเงินปลายทาง'];$groups=[];
foreach($items as $item){$sellerKey=(int)($item['seller_id']??0);if(!isset($groups[$sellerKey]))$groups[$sellerKey]=['seller_id'=>$sellerKey,'shop_name'=>$item['shop_name']?:'KitchenMate Mall','items'=>[]];$groups[$sellerKey]['items'][]=$item;}
$subtotal=(float)($order['subtotal_amount']??0);if($subtotal<=0)$subtotal=array_sum(array_map(static fn($x)=>(float)$x['subtotal'],$items));$shipping=(float)($order['shipping_amount']??0);$productDiscount=(float)($order['discount_amount']??0);$shippingDiscount=(float)($order['shipping_discount_amount']??0);$total=(float)$order['total_amount'];$latestShipping=$fulfillments[0]??null;$latestEvent=$history[0]??null;$status=(string)$order['order_status'];$statusTime=$latestShipping['delivered_at']??$latestShipping['shipped_at']??$latestShipping['updated_at']??$latestEvent['created_at']??$order['created_at'];$firstSeller=0;$firstProduct=0;foreach($items as $item){if(!$firstSeller&&!empty($item['seller_id']))$firstSeller=(int)$item['seller_id'];if(!$firstProduct)$firstProduct=(int)$item['product_id'];}
require __DIR__.'/includes/header.php';
?>
<main id="main-content" class="order-detail-page"><div class="order-detail-shell">
<header class="order-detail-titlebar"><a href="<?php echo BASE_URL;?>my-orders.php" aria-label="กลับไปยังคำสั่งซื้อของฉัน"><i class="fa-solid fa-arrow-left"></i></a><h1>รายละเอียดคำสั่งซื้อ</h1></header>
<section class="order-status-card status-<?php echo e($status);?>"><div><strong><?php echo e($statusLabels[$status]??$status);?></strong><span><?php echo date('d/m/Y H:i',strtotime($statusTime));?></span></div><i class="fa-solid <?php echo $status==='completed'?'fa-circle-check':($status==='cancelled'?'fa-circle-xmark':'fa-truck-fast');?>"></i></section>
<section class="order-card delivery-card"><a class="card-heading" href="#orderTimeline"><span>ข้อมูลการจัดส่ง</span><i class="fa-solid fa-chevron-right"></i></a>
<?php if($latestShipping&&(!empty($latestShipping['carrier'])||!empty($latestShipping['tracking_number']))):?><p class="tracking-line"><?php echo e($latestShipping['carrier']?:'ผู้ให้บริการขนส่ง');?><?php if($latestShipping['tracking_number']):?>: <strong><?php echo e($latestShipping['tracking_number']);?></strong><?php endif;?></p><?php endif;?>
<div class="shipping-current"><i class="fa-solid fa-truck"></i><div><strong><?php echo e($latestShipping?($fulfillmentLabels[$latestShipping['status']]??$statusLabels[$status]??$status):($statusLabels[$status]??$status));?></strong><time><?php echo date('d/m/Y H:i',strtotime($statusTime));?></time></div></div>
<?php if($history):?><details id="orderTimeline" class="order-timeline"><summary>ดูสถานะทั้งหมด</summary><?php foreach($history as $event):?><div><strong><?php echo e($statusLabels[$event['order_status']]??$event['order_status']);?></strong><?php if(!empty($event['note'])):?><span><?php echo e($event['note']);?></span><?php endif;?><time><?php echo date('d/m/Y H:i',strtotime($event['created_at']));?></time></div><?php endforeach;?></details><?php endif;?>
<div class="address-block"><h2>ที่อยู่ในการจัดส่ง</h2><div><i class="fa-solid fa-location-dot"></i><p><strong><?php echo e($order['shipping_name']);?></strong> <span><?php echo e($order['shipping_phone']);?></span><br><?php echo nl2br(e($order['shipping_address']));?></p></div></div></section>
<?php foreach($groups as $group):?><section class="order-card store-card"><a class="store-name" href="<?php echo $group['seller_id']?BASE_URL.'shop.php?id='.$group['seller_id']:BASE_URL.'products.php';?>"><span><i class="fa-solid fa-store"></i> <?php echo e($group['shop_name']);?></span><i class="fa-solid fa-chevron-right"></i></a><?php foreach($group['items'] as $item):?><a class="ordered-product" href="<?php echo BASE_URL;?>product-detail.php?id=<?php echo (int)$item['product_id'];?>"><img src="<?php echo e(productImageUrl($item['image_url']?:'assets/images/products/placeholder.svg'));?>" alt="<?php echo e($item['product_name']);?>"><span class="ordered-product-info"><strong><?php echo e($item['product_name']);?></strong><?php if(!empty($item['variant_name'])):?><small><?php echo e($item['variant_name']);?></small><?php endif;?><small>จำนวน x<?php echo (int)$item['quantity'];?></small></span><span class="ordered-product-price"><?php echo formatCurrency($item['price']);?></span></a><?php endforeach;?></section><?php endforeach;?>
<section class="order-card payment-summary-card"><details open><summary><span>รวมคำสั่งซื้อ</span><strong><?php echo formatCurrency($total);?></strong></summary><div class="price-breakdown"><p><span>รวมค่าสินค้า</span><strong><?php echo formatCurrency($subtotal);?></strong></p><p><span>ค่าจัดส่ง</span><strong><?php echo formatCurrency($shipping);?></strong></p><?php if($productDiscount>0):?><p class="discount"><span>ส่วนลดสินค้า</span><strong>-<?php echo formatCurrency($productDiscount);?></strong></p><?php endif;?><?php if($shippingDiscount>0):?><p class="discount"><span>ส่วนลดค่าจัดส่ง</span><strong>-<?php echo formatCurrency($shippingDiscount);?></strong></p><?php endif;?></div></details></section>
<section class="order-card after-sales-card"><h2>บริการหลังการขาย</h2><?php if(in_array($status,['shipped','completed'],true)):?><a href="<?php echo BASE_URL;?>return-request.php?order_id=<?php echo $id;?>"><i class="fa-solid fa-arrow-rotate-left"></i><span>ขอคืนเงิน/คืนสินค้า</span><i class="fa-solid fa-chevron-right"></i></a><?php endif;?><?php if($firstSeller):?><a href="<?php echo BASE_URL;?>messages.php?seller=<?php echo $firstSeller;?>&amp;product=<?php echo $firstProduct;?>"><i class="fa-regular fa-comments"></i><span>ติดต่อผู้ขาย</span><i class="fa-solid fa-chevron-right"></i></a><?php endif;?><a href="<?php echo BASE_URL;?>support.php"><i class="fa-solid fa-headset"></i><span>ศูนย์ช่วยเหลือ</span><i class="fa-solid fa-chevron-right"></i></a></section>
<section class="order-card order-meta-card"><p><span>หมายเลขคำสั่งซื้อ</span><strong><?php echo e($order['order_no']);?></strong><button type="button" id="copyOrderNo" data-order-no="<?php echo e($order['order_no']);?>">คัดลอก</button></p><p><span>ชำระผ่าน</span><strong><?php echo e($paymentLabels[$order['payment_method']]??$order['payment_method']);?></strong></p><p><span>วันที่สั่งซื้อ</span><strong><?php echo date('d/m/Y H:i',strtotime($order['created_at']));?></strong></p></section>
</div><div class="order-action-bar"><a href="<?php echo BASE_URL;?>receipt.php?id=<?php echo $id;?>">ดูเอกสาร</a><button type="button" id="buyAgain">ซื้ออีกครั้ง</button></div></main>
<script nonce="<?php echo e(cspNonce());?>">document.getElementById('copyOrderNo')?.addEventListener('click',async function(){try{await navigator.clipboard.writeText(this.dataset.orderNo);showToast('คัดลอกหมายเลขคำสั่งซื้อแล้ว','success')}catch(_){showToast('คัดลอกไม่สำเร็จ','error')}});document.getElementById('buyAgain')?.addEventListener('click',async function(){const b=this,products=<?php echo json_encode(array_map(static fn($x)=>['product_id'=>(int)$x['product_id'],'variant_id'=>(int)($x['variant_id']??0),'quantity'=>(int)$x['quantity']],$items),JSON_UNESCAPED_UNICODE);?>;b.disabled=true;b.textContent='กำลังเพิ่มสินค้า...';try{for(const p of products){const d=new FormData();d.append('action','add');d.append('csrf_token',CSRF_TOKEN);d.append('product_id',p.product_id);d.append('variant_id',p.variant_id);d.append('quantity',p.quantity);const r=await fetch(BASE_URL+'api/cart.php',{method:'POST',body:d}),j=await r.json();if(j.status!=='success')throw new Error(j.message)}location.href=BASE_URL+'cart.php'}catch(e){showToast(e.message||'ไม่สามารถเพิ่มสินค้าได้','error');b.disabled=false;b.textContent='ซื้ออีกครั้ง'}});</script>
<?php require __DIR__.'/includes/footer.php';?>
