<?php
require_once __DIR__.'/includes/functions.php';
if(isLoggedIn()){header('Location: '.BASE_URL.(isAdmin()?'admin/index.php':'index.php'));exit;}
$page_title='สมัครสมาชิก';
require_once __DIR__.'/includes/header.php';
?>
<link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/auth.css">
<div class="auth-page"><section class="auth-shell">
    <aside class="auth-intro">
        <a href="<?php echo BASE_URL; ?>index.php" class="brand-logo"><span class="brand-mark"><i class="fa-solid fa-kitchen-set"></i></span><span><strong>KitchenMart</strong><small>ของดีสำหรับทุกครัว</small></span></a>
        <p class="eyebrow">JOIN KITCHENMART</p><h1>เริ่มต้นครัวที่ใช่ด้วยบัญชีของคุณ</h1><p>สมัครฟรี ใช้เวลาไม่นาน และพร้อมสั่งซื้อสินค้าได้ทันที</p>
        <ul class="auth-benefits"><li><i class="fa-solid fa-basket-shopping"></i> สั่งซื้อและชำระเงินสะดวก</li><li><i class="fa-solid fa-location-dot"></i> เก็บข้อมูลสำหรับจัดส่ง</li><li><i class="fa-solid fa-circle-check"></i> รีวิวได้เฉพาะผู้ซื้อจริง</li></ul>
        <div class="auth-security-note"><i class="fa-solid fa-shield-halved"></i> เราจัดเก็บรหัสผ่านแบบเข้ารหัสและไม่เปิดเผยข้อมูลส่วนตัว</div>
    </aside>
    <div class="auth-card register-card">
        <header class="auth-heading"><p class="eyebrow">CREATE ACCOUNT</p><h2>สมัครสมาชิก</h2><p>กรอกข้อมูลแล้วตรวจอีเมลเพื่อเปิดใช้งานบัญชี</p></header>
        <div class="auth-error" id="authError" role="alert" aria-live="polite"><i class="fa-solid fa-circle-exclamation"></i><span></span></div>
        <form class="auth-form" id="registerForm" novalidate>
            <div class="auth-form-row"><div class="auth-field"><label for="username">ชื่อผู้ใช้ <small>ภาษาอังกฤษ/ตัวเลขเท่านั้น</small></label><div class="auth-input"><i class="fa-regular fa-user"></i><input id="username" name="username" required minlength="3" maxlength="30" pattern="[A-Za-z][A-Za-z0-9]{2,29}" autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="เช่น somchai99"></div><p class="field-hint" id="usernameHint">3–30 ตัว ต้องขึ้นต้นด้วย A–Z ห้ามเว้นวรรค จุด ขีดล่าง และอักขระพิเศษ</p></div><div class="auth-field"><label for="fullName">ชื่อ-นามสกุล</label><div class="auth-input"><i class="fa-regular fa-id-card"></i><input id="fullName" name="full_name" required minlength="2" maxlength="100" pattern="[A-Za-zก-๙ .'-]+" autocomplete="name" placeholder="สมชาย ใจดี"></div><p class="field-hint">ห้ามใส่ตัวเลข อีโมจิ หรือสัญลักษณ์ HTML</p></div></div>
            <div class="auth-form-row"><div class="auth-field"><label for="email">อีเมล</label><div class="auth-input"><i class="fa-regular fa-envelope"></i><input type="email" id="email" name="email" required maxlength="100" autocomplete="email" autocapitalize="none" spellcheck="false" placeholder="email@example.com"></div><p class="field-hint">ใช้อีเมลจริงเพื่อรับลิงก์ยืนยันบัญชี</p></div><div class="auth-field"><label for="phone">เบอร์โทรศัพท์ <small>ไม่บังคับ</small></label><div class="auth-input"><i class="fa-solid fa-phone"></i><input type="tel" id="phone" name="phone" inputmode="tel" autocomplete="tel" maxlength="12" pattern="(?:0[0-9]{8,9}|\+66[0-9]{8,9})" placeholder="0898765432"></div><p class="field-hint">ตัวเลข 9–10 หลัก ห้ามเว้นวรรคหรือใส่ขีดกลาง</p></div></div>
            <div class="auth-form-row"><div class="auth-field"><label for="password">รหัสผ่าน</label><div class="auth-input"><i class="fa-solid fa-key"></i><input type="password" id="password" name="password" required minlength="10" maxlength="72" autocomplete="new-password" placeholder="อย่างน้อย 10 ตัว"><button class="password-toggle" type="button" data-password-toggle="password" aria-label="แสดงรหัสผ่าน"><i class="fa-regular fa-eye"></i></button></div><div class="password-meter"><span id="passwordMeter"></span></div><p class="password-strength" id="passwordStrength">ต้องมีตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก และตัวเลข</p></div><div class="auth-field"><label for="passwordConfirm">ยืนยันรหัสผ่าน</label><div class="auth-input"><i class="fa-solid fa-key"></i><input type="password" id="passwordConfirm" name="password_confirm" required minlength="10" maxlength="72" autocomplete="new-password" placeholder="กรอกอีกครั้ง"><button class="password-toggle" type="button" data-password-toggle="passwordConfirm" aria-label="แสดงรหัสผ่าน"><i class="fa-regular fa-eye"></i></button></div><p class="field-hint" id="matchHint"></p></div></div>
            <label class="terms-check"><input type="checkbox" name="accept_terms" value="1" required> <span>ฉันยืนยันว่าข้อมูลถูกต้อง และยอมรับเงื่อนไขการใช้งาน ระบบจะส่งลิงก์ยืนยันไปยังอีเมลนี้</span></label>
            <input type="hidden" name="action" value="register"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken()); ?>">
            <button type="submit" id="registerBtn" class="btn btn-primary auth-submit"><span>สร้างบัญชีสมาชิก</span><i class="fa-solid fa-user-plus"></i></button>
        </form>
        <p class="auth-switch">มีบัญชีอยู่แล้ว? <a href="<?php echo BASE_URL; ?>login.php">เข้าสู่ระบบ</a></p>
    </div>
</section></div>
<script>
document.querySelectorAll('[data-password-toggle]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle),show=input.type==='password';input.type=show?'text':'password';button.innerHTML=`<i class="fa-regular fa-eye${show?'-slash':''}"></i>`;button.setAttribute('aria-label',show?'ซ่อนรหัสผ่าน':'แสดงรหัสผ่าน')}));
const password=document.getElementById('password'),confirmPassword=document.getElementById('passwordConfirm'),meter=document.getElementById('passwordMeter'),strength=document.getElementById('passwordStrength'),matchHint=document.getElementById('matchHint'),usernameInput=document.getElementById('username'),usernameHint=document.getElementById('usernameHint');
const reservedUsernames=['admin','administrator','root','system','support','staff','moderator','kitchenmart','official','null','undefined'];
function updateUsernameState(){const value=usernameInput.value,valid=/^[A-Za-z][A-Za-z0-9]{2,29}$/.test(value)&&!reservedUsernames.includes(value.toLowerCase());usernameInput.setCustomValidity(value&&!valid?'ใช้เฉพาะ A–Z และตัวเลข 3–30 ตัว ต้องเริ่มด้วยตัวอักษร และห้ามใช้ชื่อสงวน':'');usernameHint.style.color=value&&!valid?'var(--danger)':''}usernameInput.addEventListener('input',updateUsernameState);
function updatePasswordState(){const value=password.value;let score=0;if(value.length>=10)score++;if(/[A-Z]/.test(value)&&/[a-z]/.test(value))score++;if(/\d/.test(value))score++;if(/[^A-Za-z0-9\s]/.test(value))score++;const labels=['ยังไม่ปลอดภัย','พอใช้','ปานกลาง','ดี','แข็งแรง'];const colors=['#b83b32','#d96d2f','#c28a25','#4d8067','#247044'];meter.style.width=(score*25)+'%';meter.style.background=colors[score];strength.textContent=value?labels[score]:'ต้องมีตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก และตัวเลข';strength.style.color=value?colors[score]:'';const mismatch=confirmPassword.value!==''&&value!==confirmPassword.value;confirmPassword.setCustomValidity(mismatch?'รหัสผ่านไม่ตรงกัน':'');matchHint.textContent=confirmPassword.value?(mismatch?'รหัสผ่านยังไม่ตรงกัน':'รหัสผ่านตรงกันแล้ว'):'';matchHint.style.color=mismatch?'var(--danger)':'#247044'}password.addEventListener('input',updatePasswordState);confirmPassword.addEventListener('input',updatePasswordState);
function showAuthError(message,field){const box=document.getElementById('authError');box.querySelector('span').textContent=message;box.classList.add('show');document.querySelectorAll('.auth-field').forEach(el=>el.classList.remove('invalid'));if(field){const input=document.querySelector(`[name="${field}"]`);if(input){input.closest('.auth-field')?.classList.add('invalid');input.focus()}}}
document.getElementById('registerForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=document.getElementById('registerBtn');document.getElementById('authError').classList.remove('show');updatePasswordState();if(!form.reportValidity())return;button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> กำลังสร้างบัญชี';try{const response=await fetch(`${BASE_URL}api/auth.php`,{method:'POST',body:new FormData(form)});const result=await response.json();if(!response.ok||result.status!=='success')throw Object.assign(new Error(result.message||'ไม่สามารถสมัครสมาชิกได้'),{field:result.data?.field});showToast(result.message,'success');setTimeout(()=>location.href=result.data.redirect,350)}catch(error){showAuthError(error.message,error.field);button.disabled=false;button.innerHTML='<span>สร้างบัญชีสมาชิก</span><i class="fa-solid fa-user-plus"></i>'}});
</script>
<?php require_once __DIR__.'/includes/footer.php'; ?>
