<?php
$page_title='ตัวเลือกและสื่อสินค้า';
require_once __DIR__.'/includes/auth_check.php'; requireSeller();
require_once __DIR__.'/config/database.php'; require_once __DIR__.'/includes/image_upload.php'; require_once __DIR__.'/includes/security_monitor.php';
$db=(new Database())->getConnection(); $sellerId=(int)$_SESSION['user_id']; $id=(int)($_GET['id']??$_POST['product_id']??0);
$q=$db->prepare('SELECT * FROM products WHERE id=? AND seller_id=?'); $q->execute([$id,$sellerId]); $product=$q->fetch();
if(!$product){header('Location: '.BASE_URL.'my-store.php');exit;}
$message=$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 requireCsrf(false); $action=(string)($_POST['action']??'');
 try{
  protectApiMutation($db,'seller.product.media',20,60);
  if($action==='add_variant'){
   $sku=strtoupper(trim((string)($_POST['sku']??'')));$name=trim((string)($_POST['name']??''));$price=(float)($_POST['price']??0);$stock=(int)($_POST['stock']??-1);
   if(!preg_match('/^[A-Z0-9_-]{3,80}$/',$sku)||$name===''||$price<=0||$stock<0)throw new RuntimeException('ข้อมูลตัวเลือกสินค้าไม่ถูกต้อง');
   $db->prepare('INSERT INTO product_variants(product_id,sku,name,price,stock_quantity) VALUES(?,?,?,?,?)')->execute([$id,$sku,$name,$price,$stock]);$message='เพิ่มตัวเลือกสินค้าแล้ว';
  }elseif($action==='delete_variant'){$db->prepare('DELETE FROM product_variants WHERE id=? AND product_id=?')->execute([(int)($_POST['variant_id']??0),$id]);$message='ลบตัวเลือกสินค้าแล้ว';
  }elseif($action==='add_images'){
   $f=$_FILES['gallery_images']??[];$names=is_array($f['name']??null)?$f['name']:[];$c=$db->prepare('SELECT COUNT(*) FROM product_images WHERE product_id=?');$c->execute([$id]);$count=(int)$c->fetchColumn();
   if(!$names||count($names)>8||$count+count($names)>12)throw new RuntimeException('อัปโหลดได้ครั้งละไม่เกิน 8 รูป และรวมไม่เกิน 12 รูป');
   $saved=[];$db->beginTransaction();try{foreach($names as $i=>$unused){$file=['name'=>$f['name'][$i],'type'=>$f['type'][$i],'tmp_name'=>$f['tmp_name'][$i],'error'=>$f['error'][$i],'size'=>$f['size'][$i]];$path=saveProductImageUpload($file);$saved[]=$path;$db->prepare('INSERT INTO product_images(product_id,image_url,sort_order) VALUES(?,?,?)')->execute([$id,$path,$count+$i]);}$db->prepare("UPDATE products SET approval_status='pending',admin_note=NULL WHERE id=?")->execute([$id]);auditLog($db,'seller.product.images.add','product',$id,null,['count'=>count($saved)]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();foreach($saved as $path)deleteManagedUpload($path);throw $e;}$message='เพิ่มรูปแล้ว และส่งตรวจสอบอีกครั้ง';
  }elseif($action==='delete_image'){
   $s=$db->prepare('SELECT image_url FROM product_images WHERE id=? AND product_id=?');$s->execute([(int)($_POST['image_id']??0),$id]);$path=$s->fetchColumn();if($path){$db->prepare('DELETE FROM product_images WHERE id=? AND product_id=?')->execute([(int)$_POST['image_id'],$id]);$db->prepare("UPDATE products SET approval_status='pending',admin_note=NULL WHERE id=?")->execute([$id]);deleteManagedUpload($path);auditLog($db,'seller.product.image.delete','product',$id);}$message='ลบรูปแล้ว';
  }elseif($action==='save_media'){
   $primary=in_array(($_POST['primary_media_type']??''),['image','video'],true)?$_POST['primary_media_type']:'image';$old=$product['video_url']??null;$video=$old;if(uploadedFilePresent('product_video'))$video=saveProductVideoUpload($_FILES['product_video']);if($primary==='video'&&!$video)throw new RuntimeException('กรุณาอัปโหลดวิดีโอก่อนเลือกเป็นสื่อหลัก');$db->prepare("UPDATE products SET video_url=?,primary_media_type=?,approval_status='pending',admin_note=NULL WHERE id=? AND seller_id=?")->execute([$video,$primary,$id,$sellerId]);if($video!==$old&&$old)deleteManagedVideoUpload($old);auditLog($db,'seller.product.media.update','product',$id,null,['primary'=>$primary]);$product['video_url']=$video;$product['primary_media_type']=$primary;$message='บันทึกสื่อแล้ว และส่งตรวจสอบอีกครั้ง';
  }elseif($action==='delete_video'){$old=$product['video_url']??null;$db->prepare("UPDATE products SET video_url=NULL,primary_media_type='image',approval_status='pending',admin_note=NULL WHERE id=? AND seller_id=?")->execute([$id,$sellerId]);if($old)deleteManagedVideoUpload($old);auditLog($db,'seller.product.video.delete','product',$id);$product['video_url']=null;$product['primary_media_type']='image';$message='ลบวิดีโอแล้ว';}
 }catch(Throwable $e){$error=$e->getMessage();}
}
$q=$db->prepare('SELECT * FROM product_variants WHERE product_id=? ORDER BY id');$q->execute([$id]);$variants=$q->fetchAll();$q=$db->prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY sort_order,id');$q->execute([$id]);$images=$q->fetchAll();require_once __DIR__.'/includes/header.php';
?>
<link rel="stylesheet" href="<?php echo BASE_URL;?>assets/css/seller.css"><main id="main-content" class="seller-page"><div class="container"><a class="btn btn-outline" href="my-store.php">← กลับร้านค้าของฉัน</a><header class="seller-section-heading"><p class="eyebrow">PRODUCT MEDIA</p><h1><?php echo e($product['name']);?></h1><p>จัดการตัวเลือก รูป และวิดีโอ การเปลี่ยนสื่อจะส่งสินค้าให้แอดมินตรวจสอบอีกครั้ง</p></header><?php if($message):?><p class="seller-success"><?php echo e($message);?></p><?php endif;?><?php if($error):?><p class="seller-error"><?php echo e($error);?></p><?php endif;?><div class="seller-media-grid">
<section class="admin-panel"><h2>ตัวเลือกสินค้า / SKU</h2><p>สำหรับสี ขนาด หรือรุ่นที่ราคาและสต็อกต่างกัน</p><form method="post" class="admin-form-grid"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><input type="hidden" name="action" value="add_variant"><input name="sku" placeholder="SKU เช่น PAN-BLACK-28" required><input name="name" placeholder="สีดำ 28 ซม." required><input type="number" name="price" min=".01" step=".01" value="<?php echo e($product['price']);?>" required><input type="number" name="stock" min="0" value="0" required><button class="btn btn-primary">เพิ่มตัวเลือก</button></form><?php foreach($variants as $x):?><form method="post" class="seller-media-row"><span><?php echo e($x['name'].' · '.$x['sku']);?> · <?php echo formatCurrency($x['price']);?> · <?php echo (int)$x['stock_quantity'];?> ชิ้น</span><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><input type="hidden" name="variant_id" value="<?php echo (int)$x['id'];?>"><button class="btn btn-outline" name="action" value="delete_variant">ลบ</button></form><?php endforeach;?></section>
<section class="admin-panel"><h2>รูปภาพเพิ่มเติม</h2><p>รวมไม่เกิน 12 รูป รูปละไม่เกิน 3 MB</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><input type="hidden" name="action" value="add_images"><input type="file" name="gallery_images[]" accept="image/jpeg,image/png,image/webp" multiple required><button class="btn btn-primary">อัปโหลดรูป</button></form><div class="seller-media-gallery"><?php foreach($images as $x):?><form method="post"><img src="<?php echo e(productImageUrl($x['image_url']));?>" alt=""><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><input type="hidden" name="image_id" value="<?php echo (int)$x['id'];?>"><button class="btn btn-outline" name="action" value="delete_image">ลบรูป</button></form><?php endforeach;?></div></section>
<section class="admin-panel"><h2>วิดีโอและสื่อหลัก</h2><p>MP4 หรือ WebM ไม่เกิน 50 MB และเลือกสื่อแรกที่ลูกค้าจะเห็น</p><?php if(!empty($product['video_url'])):?><video class="seller-product-video" controls muted playsinline preload="metadata"><source src="<?php echo e(BASE_URL.ltrim($product['video_url'],'/'));?>"></video><?php endif;?><form method="post" enctype="multipart/form-data" class="admin-form-grid"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><input type="hidden" name="action" value="save_media"><fieldset><legend>สื่อหลัก</legend><label><input type="radio" name="primary_media_type" value="image" <?php echo ($product['primary_media_type']??'image')==='image'?'checked':'';?>> รูปภาพ</label> <label><input type="radio" name="primary_media_type" value="video" <?php echo ($product['primary_media_type']??'image')==='video'?'checked':'';?>> วิดีโอ</label></fieldset><input type="file" name="product_video" accept="video/mp4,video/webm"><button class="btn btn-primary">บันทึกสื่อสินค้า</button></form><?php if(!empty($product['video_url'])):?><form method="post"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo $id;?>"><button class="btn btn-outline" name="action" value="delete_video">ลบวิดีโอ</button></form><?php endif;?></section>
</div></div></main><?php require_once __DIR__.'/includes/footer.php';?>
