<?php
require_once __DIR__ . '/includes/auth_check.php';
requireLogin();
require_once __DIR__ . '/config/database.php';
$db = (new Database())->getConnection();
if (!$db) { http_response_code(503); exit('ไม่สามารถเชื่อมต่อฐานข้อมูลได้'); }
$stmt = $db->prepare('SELECT full_name,email,phone,address,email_verified_at FROM users WHERE id=? LIMIT 1');
$stmt->execute([(int)$_SESSION['user_id']]);
$user = $stmt->fetch();
if (!$user) { header('Location: '.BASE_URL.'login.php'); exit; }
$categories = $db->query('SELECT id,name FROM categories ORDER BY id')->fetchAll();
$profileStmt = $db->prepare('SELECT status,shop_name,admin_note FROM seller_profiles WHERE user_id=? LIMIT 1');
$profileStmt->execute([(int)$_SESSION['user_id']]);
$sellerProfile = $profileStmt->fetch() ?: null;
$page_title = 'เปิดร้านกับ KitchenMart';
require_once __DIR__ . '/includes/header.php';
?>
<link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/seller.css">
<div class="seller-page"><div class="container">
    <nav class="seller-breadcrumb"><a href="<?php echo BASE_URL; ?>profile.php">บัญชีของฉัน</a><i class="fa-solid fa-chevron-right"></i><span>เปิดร้านกับ KitchenMart</span></nav>
    <section class="seller-hero"><div><p class="eyebrow">KITCHENMART SELLER</p><h1>เริ่มขายของดี<br>ให้ถึงทุกครัว</h1><p>ใช้บัญชีเดิมของคุณเปิดร้านได้ในไม่กี่ขั้นตอน เราจะตรวจข้อมูลร้านก่อนเปิดให้เริ่มลงสินค้า</p><a class="btn" href="#sellerApplication">เริ่มสมัครเป็นผู้ขาย <i class="fa-solid fa-arrow-down"></i></a></div><aside><span><i class="fa-solid fa-store"></i></span><strong>ทุกอย่างที่ต้องใช้<br>อยู่ในบัญชีเดียว</strong><ul><li><i class="fa-solid fa-check"></i> เพิ่มสินค้าและควบคุมสต็อก</li><li><i class="fa-solid fa-check"></i> รับและจัดการออเดอร์</li><li><i class="fa-solid fa-check"></i> ดูยอดขายอย่างเป็นระบบ</li></ul></aside></section>
    <ol class="seller-steps"><li class="active"><b>1</b><span><strong>ข้อมูลร้าน</strong><small>บอกเราว่าคุณขายอะไร</small></span></li><li><b>2</b><span><strong>รับเงินและคืนสินค้า</strong><small>ตั้งค่าการรับเงิน</small></span></li><li><b>3</b><span><strong>ส่งคำขอ</strong><small>รอทีมงานตรวจสอบ</small></span></li></ol>
    <?php if (!$user['email_verified_at']): ?>
        <section class="seller-email-note"><i class="fa-solid fa-envelope-circle-check"></i><div><strong>ยืนยันอีเมลก่อนเริ่มสมัคร</strong><p>เพื่อความปลอดภัยของร้าน กรุณายืนยันอีเมลของบัญชีนี้ก่อนส่งคำขอเปิดร้าน</p></div><a class="btn btn-primary" href="<?php echo BASE_URL; ?>check-email.php">ไปยืนยันอีเมล</a></section>
    <?php elseif ($sellerProfile): ?>
        <section class="seller-email-note"><i class="fa-solid <?php echo $sellerProfile['status']==='approved'?'fa-circle-check':'fa-clock'; ?>"></i><div><strong><?php echo $sellerProfile['status']==='approved'?'ร้านของคุณได้รับอนุมัติแล้ว':($sellerProfile['status']==='rejected'?'คำขอเปิดร้านยังไม่ได้รับอนุมัติ':'ได้รับคำขอเปิดร้านแล้ว'); ?></strong><p><?php echo $sellerProfile['status']==='approved'?'ตอนนี้คุณมีสถานะผู้ขายแล้ว ระบบจัดการสินค้าและยอดถอนจะเปิดในขั้นต่อไป':e($sellerProfile['admin_note'] ?: 'ทีมงานกำลังตรวจสอบข้อมูลร้าน '.$sellerProfile['shop_name'].' และข้อมูลรับเงินของคุณ'); ?></p></div><a class="btn btn-primary" href="<?php echo BASE_URL; ?>profile.php">กลับไปบัญชีของฉัน</a></section>
    <?php else: ?>
    <section class="seller-application" id="sellerApplication" data-seller-wizard><aside><p class="eyebrow">BEFORE YOU START</p><h2>ใช้เวลาไม่เกิน<br>3 นาที</h2><p>เตรียมชื่อร้าน ที่อยู่รับคืนสินค้า และช่องทางรับเงินไว้ให้พร้อม</p><div><i class="fa-solid fa-shield-heart"></i><span><strong>ข้อมูลปลอดภัย</strong><small>ข้อมูลรับเงินจะแสดงเฉพาะทีมตรวจสอบ</small></span></div></aside>
        <form class="seller-form" novalidate><input type="hidden" name="action" value="apply"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken()); ?>">
            <fieldset data-step="1"><header><p class="eyebrow">STEP 01 / 03</p><h2>ร้านของคุณชื่ออะไร?</h2><p>เริ่มจากข้อมูลพื้นฐานที่ลูกค้าจะเห็นเมื่อเข้าหน้าร้าน</p></header><div class="seller-fields"><label>ชื่อร้าน<input name="shop_name" required maxlength="80" placeholder="เช่น ครัวบ้านแม่"></label><label>หมวดสินค้าหลัก<select name="category" required><option value="" selected disabled>เลือกหมวดสินค้า</option><?php foreach($categories as $category): ?><option value="<?php echo (int)$category['id']; ?>"><?php echo e($category['name']); ?></option><?php endforeach; ?></select></label><label class="full">คำอธิบายร้าน<textarea name="description" rows="4" maxlength="500" placeholder="บอกลูกค้าสั้น ๆ ว่าร้านของคุณคัดสรรสินค้าแบบใด"></textarea><small>ไม่เกิน 500 ตัวอักษร สามารถแก้ไขได้ภายหลัง</small></label></div><footer><span>ขั้นตอนที่ 1 จาก 3</span><button type="button" class="btn btn-primary" data-next>ไปต่อ <i class="fa-solid fa-arrow-right"></i></button></footer></fieldset>
            <fieldset data-step="2" hidden><header><p class="eyebrow">STEP 02 / 03</p><h2>ให้เราติดต่อและโอนเงินอย่างไร?</h2><p>ข้อมูลนี้ใช้สำหรับตรวจสอบและตั้งค่าการรับเงินหลังได้รับอนุมัติ</p></header><div class="seller-fields"><label>เบอร์โทรศัพท์ติดต่อ<input name="phone" required maxlength="20" value="<?php echo e($user['phone']); ?>" placeholder="0812345678"></label><label>วิธีรับเงิน<select name="payout" required><option value="" selected disabled>เลือกวิธีรับเงิน</option><option value="promptpay">PromptPay</option><option value="bank">บัญชีธนาคาร</option></select></label><label class="full">ชื่อบัญชีรับเงิน<input name="payout_name" required maxlength="100" value="<?php echo e($user['full_name']); ?>" placeholder="ชื่อ-นามสกุลตามบัญชี"></label><label class="full">เลข PromptPay / เลขบัญชี<input name="payout_number" required maxlength="100" inputmode="numeric" placeholder="กรอกเลขที่ใช้รับเงิน"></label><label class="full">ที่อยู่รับคืนสินค้า<textarea name="return_address" rows="4" required maxlength="1000" placeholder="บ้านเลขที่ ถนน แขวง/ตำบล เขต/อำเภอ จังหวัด รหัสไปรษณีย์"><?php echo e($user['address']); ?></textarea><small>ลูกค้าจะใช้ที่อยู่นี้เฉพาะเมื่อมีการคืนสินค้าที่ได้รับอนุมัติ</small></label></div><footer><button type="button" class="btn btn-outline" data-back><i class="fa-solid fa-arrow-left"></i> ย้อนกลับ</button><button type="button" class="btn btn-primary" data-next>ตรวจสอบข้อมูล <i class="fa-solid fa-arrow-right"></i></button></footer></fieldset>
            <fieldset data-step="3" hidden><header><p class="eyebrow">STEP 03 / 03</p><h2>พร้อมส่งคำขอแล้ว</h2><p>ตรวจสอบข้อมูลอีกครั้ง ทีมงานจะแจ้งผลให้ทราบผ่านอีเมลของคุณ</p></header><div class="seller-review" data-review></div><label class="seller-consent"><input type="checkbox" required><span>ฉันยืนยันว่าข้อมูลร้านและข้อมูลรับเงินถูกต้อง และยอมรับเงื่อนไขสำหรับผู้ขาย</span></label><footer><button type="button" class="btn btn-outline" data-back><i class="fa-solid fa-arrow-left"></i> แก้ไขข้อมูล</button><button type="submit" class="btn btn-primary">ส่งคำขอเปิดร้าน <i class="fa-solid fa-paper-plane"></i></button></footer></fieldset>
            <section class="seller-ready" hidden><span><i class="fa-solid fa-check"></i></span><p class="eyebrow">REQUEST READY</p><h2>ข้อมูลพร้อมส่งคำขอแล้ว</h2><p>นี่คือหน้าต้นแบบของขั้นตอนสมัครผู้ขาย เมื่อเปิดระบบอนุมัติ ข้อมูลชุดนี้จะถูกส่งให้ทีมงานตรวจสอบและแสดงสถานะในบัญชีของคุณ</p><a href="<?php echo BASE_URL; ?>profile.php" class="btn btn-primary">กลับไปบัญชีของฉัน</a></section>
        </form>
    </section><?php endif; ?>
</div></div>
<script nonce="<?php echo e(cspNonce()); ?>">
document.querySelectorAll('[data-seller-wizard]').forEach(wizard=>{const form=wizard.querySelector('form'),steps=[...form.querySelectorAll('[data-step]')],dots=[...document.querySelectorAll('.seller-steps li')];let current=0;const escape=v=>String(v||'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const show=index=>{current=index;steps.forEach((step,i)=>{step.hidden=i!==index});dots.forEach((dot,i)=>dot.classList.toggle('active',i<=index));if(index===2){const f=form.elements;form.querySelector('[data-review]').innerHTML=`<dl><div><dt>ชื่อร้าน</dt><dd>${escape(f.shop_name.value)}</dd></div><div><dt>หมวดสินค้าหลัก</dt><dd>${escape(f.category.selectedOptions[0]?.text)}</dd></div><div><dt>เบอร์โทรศัพท์</dt><dd>${escape(f.phone.value)}</dd></div><div><dt>วิธีรับเงิน</dt><dd>${escape(f.payout.value)}</dd></div><div><dt>ที่อยู่รับคืนสินค้า</dt><dd>${escape(f.return_address.value)}</dd></div></dl>`}wizard.scrollIntoView({behavior:'smooth',block:'start'})};form.querySelectorAll('[data-next]').forEach(button=>button.onclick=()=>{const fields=[...steps[current].querySelectorAll('input,select,textarea')].filter(field=>field.required);if(fields.every(field=>field.reportValidity()))show(current+1)});form.querySelectorAll('[data-back]').forEach(button=>button.onclick=()=>show(current-1));form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;steps.forEach(step=>step.hidden=true);form.querySelector('.seller-ready').hidden=false;dots.forEach(dot=>dot.classList.add('active'))}});
</script>
<script>
document.querySelectorAll('[data-seller-wizard] .seller-form').forEach(form=>{form.onsubmit=async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type="submit"]'),original=button.innerHTML;button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> กำลังส่งคำขอ';try{const response=await fetch(`${BASE_URL}api/seller.php`,{method:'POST',body:new FormData(form)}),result=await response.json();if(!response.ok||result.status!=='success')throw new Error(result.message||'ไม่สามารถส่งคำขอได้');form.querySelectorAll('fieldset').forEach(step=>step.hidden=true);form.querySelector('.seller-ready').hidden=false;form.querySelector('.seller-ready>p:not(.eyebrow)').textContent=result.message;document.querySelectorAll('.seller-steps li').forEach(item=>item.classList.add('active'));}catch(error){showToast(error.message,'error');button.disabled=false;button.innerHTML=original;}}});
</script>
<script>
document.querySelectorAll('[data-seller-wizard] .seller-form').forEach(form=>{const method=form.elements.payout,number=form.elements.payout_number,numberLabel=number.closest('label'),bankLabel=document.createElement('label');bankLabel.className='full';bankLabel.hidden=true;bankLabel.innerHTML='ธนาคาร<select name="payout_bank" disabled><option value="" selected disabled>เลือกธนาคาร</option><option>กสิกรไทย</option><option>กรุงไทย</option><option>กรุงเทพ</option><option>ไทยพาณิชย์</option><option>กรุงศรีอยุธยา</option><option>ทหารไทยธนชาต</option><option>ออมสิน</option><option>ธ.ก.ส.</option><option>ยูโอบี</option><option>ซีไอเอ็มบี ไทย</option></select>';numberLabel.before(bankLabel);const bank=bankLabel.querySelector('select');const update=()=>{const isBank=method.value==='bank';bankLabel.hidden=!isBank;bank.disabled=!isBank;bank.required=isBank;numberLabel.childNodes[0].nodeValue=isBank?'เลขบัญชี ':'เลข PromptPay ';number.placeholder=isBank?'กรอกเลขบัญชี':'กรอกเบอร์มือถือหรือเลข PromptPay'};method.addEventListener('change',update);update();});
</script>
<script>
document.querySelectorAll('[data-seller-wizard] .seller-form').forEach(form=>{const method=form.elements.payout,owner=form.elements.payout_name,number=form.elements.payout_number,ownerLabel=owner.closest('label'),numberLabel=number.closest('label'),bank=form.elements.payout_bank,bankLabel=bank.closest('label');if(![...method.options].some(option=>option.value==='both'))method.add(new Option('PromptPay และบัญชีธนาคาร','both'));const bankOwnerLabel=document.createElement('label'),bankNumberLabel=document.createElement('label');bankOwnerLabel.className=bankNumberLabel.className='full';bankOwnerLabel.hidden=bankNumberLabel.hidden=true;bankOwnerLabel.innerHTML='ชื่อเจ้าของบัญชี<input name="bank_owner" maxlength="100" placeholder="ชื่อ-นามสกุลตามบัญชี">';bankNumberLabel.innerHTML='เลขบัญชี<input name="bank_number" maxlength="100" inputmode="numeric" placeholder="กรอกเลขบัญชี">';bankLabel.after(bankOwnerLabel,bankNumberLabel);const bankOwner=form.elements.bank_owner,bankNumber=form.elements.bank_number;const updateDetails=()=>{const isBank=method.value==='bank'||method.value==='both',isPrompt=method.value==='promptpay'||method.value==='both';ownerLabel.childNodes[0].nodeValue=isPrompt?'ชื่อเจ้าของ PromptPay ':'ชื่อเจ้าของบัญชี ';numberLabel.childNodes[0].nodeValue=isPrompt?'เลข PromptPay ':'เลขบัญชี ';number.placeholder=isPrompt?'กรอกเบอร์มือถือหรือเลข PromptPay':'กรอกเลขบัญชี';bankLabel.hidden=!isBank;bank.disabled=!isBank;bank.required=isBank;bankOwnerLabel.hidden=bankNumberLabel.hidden=!isBank;bankOwner.disabled=bankNumber.disabled=!isBank;bankOwner.required=bankNumber.required=isBank};method.addEventListener('change',updateDetails);updateDetails();});
</script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
