<?php
$page_title='โปรโมชัน Marketplace';require_once __DIR__.'/includes/auth_check.php';requireSeller();require_once __DIR__.'/config/database.php';$db=(new Database())->getConnection();$seller=(int)$_SESSION['user_id'];$message=$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf(false);try{$action=$_POST['action']??'';
 if($action==='sale'){$id=(int)$_POST['product_id'];$price=(float)$_POST['sale_price'];$compare=(float)$_POST['compare_at_price'];$start=$_POST['starts_at'];$end=$_POST['ends_at'];if($price<=0||$compare<=$price||strtotime($end)<=strtotime($start))throw new RuntimeException('ราคาและช่วงเวลาไม่ถูกต้อง');$q=$db->prepare('UPDATE products SET compare_at_price=?,sale_price=?,sale_starts_at=?,sale_ends_at=?,sale_stock=?,video_url=?,fulfillment_type=? WHERE id=? AND seller_id=?');$q->execute([$compare,$price,$start,$end,(int)$_POST['sale_stock'],trim($_POST['video_url']),$_POST['fulfillment_type']==='platform'?'platform':'seller',$id,$seller]);$message='บันทึก Flash Sale แล้ว';}
 elseif($action==='coupon'){$code=strtoupper(trim($_POST['code']));$type=$_POST['discount_type'];$value=(float)$_POST['discount_value'];if(!preg_match('/^[A-Z0-9_-]{4,40}$/',$code)||!in_array($type,['percent','fixed','free_shipping'],true))throw new RuntimeException('ข้อมูลคูปองไม่ถูกต้อง');$q=$db->prepare('INSERT INTO coupons(seller_id,code,title,description,discount_type,discount_value,min_order_amount,usage_limit,per_user_limit,starts_at,ends_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$seller,$code,trim($_POST['title']),'คูปองจากร้าน',$type,$value,(float)$_POST['min_order_amount'],(int)$_POST['usage_limit']?:null,max(1,(int)$_POST['per_user_limit']),$_POST['starts_at'],$_POST['ends_at']]);$message='สร้างคูปองร้านแล้ว';}
 elseif($action==='bundle'){$ids=array_values(array_unique(array_map('intval',$_POST['products']??[])));if(count($ids)<2)throw new RuntimeException('เลือกสินค้าอย่างน้อย 2 รายการ');$db->beginTransaction();$q=$db->prepare('INSERT INTO product_bundles(seller_id,title,discount_percent,minimum_items,starts_at,ends_at) VALUES(?,?,?,?,?,?)');$q->execute([$seller,trim($_POST['title']),(float)$_POST['discount_percent'],count($ids),$_POST['starts_at'],$_POST['ends_at']]);$bundle=(int)$db->lastInsertId();$check=$db->prepare('SELECT id FROM products WHERE id=? AND seller_id=?');$add=$db->prepare('INSERT INTO product_bundle_items(bundle_id,product_id) VALUES(?,?)');foreach($ids as $id){$check->execute([$id,$seller]);if(!$check->fetchColumn())throw new RuntimeException('พบสินค้าที่ไม่ใช่ของร้าน');$add->execute([$bundle,$id]);}$db->commit();$message='สร้าง Bundle Deal แล้ว';}
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}}
$p=$db->prepare('SELECT * FROM products WHERE seller_id=? ORDER BY created_at DESC');$p->execute([$seller]);$products=$p->fetchAll();$c=$db->prepare('SELECT * FROM coupons WHERE seller_id=? ORDER BY id DESC');$c->execute([$seller]);$coupons=$c->fetchAll();require_once __DIR__.'/includes/header.php';$start=date('Y-m-d\TH:i');$end=date('Y-m-d\TH:i',strtotime('+7 days'));?>
<link rel="stylesheet" href="<?php echo BASE_URL;?>assets/css/seller.css"><div class="container marketplace-manager"><header><a href="<?php echo BASE_URL;?>seller-dashboard.php">← Seller Center</a><h1>โปรโมชันและการขาย</h1><p>จัดการ Flash Sale, คูปองร้าน, Bundle, วิดีโอ และรูปแบบการจัดส่ง</p></header><?php if($message):?><p class="seller-success"><?php echo e($message);?></p><?php endif;?><?php if($error):?><p class="seller-error"><?php echo e($error);?></p><?php endif;?><div class="manager-grid">
<section class="admin-panel"><h2>Flash Sale / วิดีโอ / Fulfilled</h2><form method="post" class="admin-form-grid"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="action" value="sale"><select name="product_id" required><?php foreach($products as $x):?><option value="<?php echo $x['id'];?>"><?php echo e($x['name']);?></option><?php endforeach;?></select><input type="number" step=".01" name="compare_at_price" placeholder="ราคาเดิม" required><input type="number" step=".01" name="sale_price" placeholder="ราคาลด" required><input type="number" name="sale_stock" min="1" value="10"><input type="datetime-local" name="starts_at" value="<?php echo $start;?>" required><input type="datetime-local" name="ends_at" value="<?php echo $end;?>" required><input name="video_url" placeholder="URL วิดีโอ YouTube"><select name="fulfillment_type"><option value="seller">ร้านจัดส่ง</option><option value="platform">MALL Fulfilled</option></select><button class="btn btn-primary">บันทึก</button></form></section>
<section class="admin-panel"><h2>คูปองเฉพาะร้าน</h2><form method="post" class="admin-form-grid"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="action" value="coupon"><input name="code" placeholder="SHOP10" required><input name="title" placeholder="ชื่อคูปอง" required><select name="discount_type"><option value="percent">เปอร์เซ็นต์</option><option value="fixed">จำนวนเงิน</option><option value="free_shipping">ส่งฟรี</option></select><input type="number" step=".01" name="discount_value" value="10"><input type="number" name="min_order_amount" value="0"><input type="number" name="usage_limit" value="100"><input type="number" name="per_user_limit" value="1"><input type="datetime-local" name="starts_at" value="<?php echo $start;?>"><input type="datetime-local" name="ends_at" value="<?php echo $end;?>"><button class="btn btn-primary">สร้างคูปอง</button></form></section>
<section class="admin-panel"><h2>Bundle Deal</h2><form method="post" class="admin-form-grid"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="action" value="bundle"><input name="title" placeholder="ซื้อคู่คุ้มกว่า" required><input type="number" step=".01" name="discount_percent" min="1" max="90" value="5"><div class="bundle-products"><?php foreach($products as $x):?><label><input type="checkbox" name="products[]" value="<?php echo $x['id'];?>"> <?php echo e($x['name']);?></label><?php endforeach;?></div><input type="datetime-local" name="starts_at" value="<?php echo $start;?>"><input type="datetime-local" name="ends_at" value="<?php echo $end;?>"><button class="btn btn-primary">สร้าง Bundle</button></form></section></div></div><?php require_once __DIR__.'/includes/footer.php';?>
