<?php
$page_title='ศูนย์ช่วยเหลือ';
require_once __DIR__.'/includes/auth_check.php'; requireLogin(); require_once __DIR__.'/config/database.php';
$db=(new Database())->getConnection(); $uid=(int)$_SESSION['user_id']; $message=''; $error='';
$categories=['order'=>'คำสั่งซื้อ','payment'=>'การชำระเงิน','return'=>'คืนสินค้า','product'=>'สินค้า','account'=>'บัญชีผู้ใช้','privacy'=>'ข้อมูลส่วนบุคคล','other'=>'เรื่องอื่น'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 requireCsrf(false); $action=$_POST['action']??'';
 try{
  if($action==='create'){
   $subject=trim($_POST['subject']??'');$body=trim($_POST['message']??'');$category=$_POST['category']??'other';$orderId=(int)($_POST['order_id']??0);
   if(!isset($categories[$category])||mb_strlen($subject)<5||mb_strlen($subject)>180||mb_strlen($body)<10||mb_strlen($body)>5000)throw new RuntimeException('กรุณากรอกหัวข้อ 5–180 ตัวอักษร และรายละเอียด 10–5,000 ตัวอักษร');
   if($orderId){$check=$db->prepare('SELECT id FROM orders WHERE id=? AND user_id=?');$check->execute([$orderId,$uid]);if(!$check->fetchColumn())throw new RuntimeException('ไม่พบคำสั่งซื้อที่เลือก');}
   $db->beginTransaction();$ticketNo='KM'.date('ymd').strtoupper(bin2hex(random_bytes(3)));$stmt=$db->prepare('INSERT INTO support_tickets(ticket_no,user_id,order_id,category,subject,status) VALUES(?,?,?,?,?,?)');$stmt->execute([$ticketNo,$uid,$orderId?:null,$category,$subject,'waiting_staff']);$ticketId=(int)$db->lastInsertId();$db->prepare('INSERT INTO support_messages(ticket_id,sender_user_id,message,is_staff) VALUES(?,?,?,0)')->execute([$ticketId,$uid,$body]);createRoleNotification($db,'admin','support','เคสช่วยเหลือใหม่ '.$ticketNo,$subject,BASE_URL.'admin/support.php?id='.$ticketId);auditLog($db,'support.ticket.create','support_ticket',$ticketId,null,['category'=>$category]);$db->commit();$message='ส่งเรื่องเรียบร้อย หมายเลขเคส '.$ticketNo;
  }elseif($action==='reply'){
   $id=(int)($_POST['ticket_id']??0);$body=trim($_POST['message']??'');if(mb_strlen($body)<2||mb_strlen($body)>5000)throw new RuntimeException('ข้อความต้องมี 2–5,000 ตัวอักษร');
   $stmt=$db->prepare("SELECT id,status FROM support_tickets WHERE id=? AND user_id=? AND status<>'closed'");$stmt->execute([$id,$uid]);if(!$stmt->fetch())throw new RuntimeException('ไม่พบเคสหรือเคสถูกปิดแล้ว');$db->prepare('INSERT INTO support_messages(ticket_id,sender_user_id,message,is_staff) VALUES(?,?,?,0)')->execute([$id,$uid,$body]);$db->prepare("UPDATE support_tickets SET status='waiting_staff',last_message_at=NOW() WHERE id=?")->execute([$id]);$message='ส่งข้อความเพิ่มเติมแล้ว';
  }
 }catch(Throwable $e){if($db&&$db->inTransaction())$db->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'ไม่สามารถดำเนินการได้';}
}
$orders=$db->prepare('SELECT id,order_no FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 30');$orders->execute([$uid]);$orders=$orders->fetchAll();
$tickets=$db->prepare('SELECT t.*,o.order_no FROM support_tickets t LEFT JOIN orders o ON o.id=t.order_id WHERE t.user_id=? ORDER BY t.last_message_at DESC');$tickets->execute([$uid]);$tickets=$tickets->fetchAll();
$selected=null;$messages=[];$selectedId=(int)($_GET['id']??0);if($selectedId){$s=$db->prepare('SELECT * FROM support_tickets WHERE id=? AND user_id=?');$s->execute([$selectedId,$uid]);$selected=$s->fetch();if($selected){$s=$db->prepare('SELECT m.*,u.username FROM support_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.ticket_id=? ORDER BY m.id');$s->execute([$selectedId]);$messages=$s->fetchAll();}}
require __DIR__.'/includes/header.php';
?>
<div class="container" style="max-width:1050px;padding:34px 16px 70px"><header style="margin-bottom:24px"><p class="eyebrow">CUSTOMER CARE</p><h1>ศูนย์ช่วยเหลือ</h1><p>ติดตามทุกเรื่องด้วยหมายเลขเคสและสนทนากับทีมงานได้ในหน้าเดียว</p></header><?php if($message):?><div class="alert alert-success"><?php echo e($message);?></div><?php endif;?><?php if($error):?><div class="alert alert-error"><?php echo e($error);?></div><?php endif;?>
<div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,.85fr);gap:22px" class="support-grid"><section style="background:#fff;border:1px solid var(--border-color);padding:24px"><h2>แจ้งเรื่องใหม่</h2><form method="post" style="display:grid;gap:14px"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="action" value="create"><label>ประเภท<select name="category" required><?php foreach($categories as $key=>$label):?><option value="<?php echo e($key);?>"><?php echo e($label);?></option><?php endforeach;?></select></label><label>คำสั่งซื้อ (ถ้ามี)<select name="order_id"><option value="">ไม่เกี่ยวกับคำสั่งซื้อ</option><?php foreach($orders as $o):?><option value="<?php echo (int)$o['id'];?>"><?php echo e($o['order_no']);?></option><?php endforeach;?></select></label><label>หัวข้อ<input name="subject" maxlength="180" required></label><label>รายละเอียด<textarea name="message" rows="6" maxlength="5000" required></textarea></label><button class="btn btn-primary" type="submit">ส่งเรื่องให้ทีมงาน</button></form></section>
<section style="background:#fff;border:1px solid var(--border-color);padding:24px"><h2>เคสของฉัน</h2><?php if(!$tickets):?><p>ยังไม่มีเคสช่วยเหลือ</p><?php else:?><?php foreach($tickets as $t):?><a href="?id=<?php echo (int)$t['id'];?>" style="display:block;padding:14px 0;border-bottom:1px solid var(--border-color)"><strong><?php echo e($t['subject']);?></strong><br><small><?php echo e($t['ticket_no']);?> · <?php echo e($categories[$t['category']]??$t['category']);?> · <?php echo e($t['status']);?></small></a><?php endforeach;?><?php endif;?></section></div>
<?php if($selected):?><section style="background:#fff;border:1px solid var(--border-color);padding:24px;margin-top:22px"><h2><?php echo e($selected['subject']);?> <small><?php echo e($selected['ticket_no']);?></small></h2><?php foreach($messages as $m):?><article style="max-width:80%;margin:12px <?php echo $m['is_staff']?'auto':'0';?> 12px <?php echo $m['is_staff']?'0':'auto';?>;padding:14px;background:<?php echo $m['is_staff']?'#eef5f1':'#fff7ed';?>"><strong><?php echo $m['is_staff']?'ทีมงาน':e($m['username']??'คุณ');?></strong><p><?php echo nl2br(e($m['message']));?></p><small><?php echo date('d/m/Y H:i',strtotime($m['created_at']));?></small></article><?php endforeach;?><?php if($selected['status']!=='closed'):?><form method="post" style="display:flex;gap:10px;margin-top:18px"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="action" value="reply"><input type="hidden" name="ticket_id" value="<?php echo (int)$selected['id'];?>"><input name="message" maxlength="5000" placeholder="พิมพ์ข้อความเพิ่มเติม" required style="flex:1"><button class="btn btn-primary">ส่ง</button></form><?php endif;?></section><?php endif;?></div>
<style>@media(max-width:720px){.support-grid{grid-template-columns:1fr!important}}</style>
<?php require __DIR__.'/includes/footer.php';?>
