<?php
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';requireAdmin();$db=(new Database())->getConnection();if(!$db)die('Database unavailable');$base=$db->query('SELECT * FROM behavior_baselines ORDER BY id')->fetchAll();$run=$db->query('SELECT * FROM behavior_experiments ORDER BY id DESC LIMIT 1')->fetch();
if(($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename=behavior-analysis.csv');$o=fopen('php://output','w');fwrite($o,"\xEF\xBB\xBF");fputcsv($o,['Metric (English)','Value','Thai description']);if($run)foreach([['Accuracy',$run['accuracy'],'ความถูกต้องรวม'],['Precision',$run['precision_score'],'ความแม่นยำของการแจ้งเตือน'],['Detection Rate / Recall',$run['recall_score'],'อัตราตรวจจับ'],['F1-score',$run['f1_score'],'สมดุล Precision/Recall'],['False Positive Rate',$run['false_positive_rate'],'อัตราแจ้งผู้ใช้ปกติผิด'],['Detection Time (ms)',$run['avg_detection_time_ms'],'เวลาตรวจจับเฉลี่ย']]as$r)fputcsv($o,$r);fputcsv($o,[]);fputcsv($o,['Feature','Mean','SD','Threshold','Samples']);foreach($base as$b)fputcsv($o,[$b['feature_name_en'],$b['mean_value'],$b['sd_value'],'>'.$b['threshold_value'],$b['sample_count']]);exit;}
$page_title='Behavior Analytics';include __DIR__.'/../includes/admin_header.php';?>
<section class="admin-page-head"><div><span class="eyebrow">SECURITY DATA ANALYSIS</span><h1>Behavior Analytics</h1><p>ข้อมูลผู้ใช้จำลอง 100 คน ระยะเวลา 30 วัน แยก Normal และ Suspicious อย่างชัดเจน</p></div><a class="btn btn-primary" href="?export=csv"><i class="fa-solid fa-file-excel"></i> Export for Excel</a></section>
<?php if(!$run):?><section class="admin-panel"><p>ยังไม่มีผลทดลอง กรุณารันเครื่องมือสร้างข้อมูล วิเคราะห์ Baseline และทดลองตรวจจับ</p></section><?php else:?>
<div class="admin-stats-grid"><?php foreach(['Accuracy'=>'accuracy','Precision'=>'precision_score','Detection Rate'=>'recall_score','F1-score'=>'f1_score','False Positive Rate'=>'false_positive_rate']as$n=>$k):?><article><small><?=$n?></small><strong><?=number_format($run[$k]*100,2)?>%</strong></article><?php endforeach?></div>
<section class="admin-panel"><div class="admin-panel-head"><div><h2>Confusion Matrix</h2><small>Actual versus Predicted</small></div></div><div class="admin-table-wrap"><table><thead><tr><th></th><th>Actual Normal</th><th>Actual Suspicious</th></tr></thead><tbody><tr><th>Predicted Normal</th><td><?=$run['true_negative']?> TN</td><td><?=$run['false_negative']?> FN</td></tr><tr><th>Predicted Suspicious</th><td><?=$run['false_positive']?> FP</td><td><?=$run['true_positive']?> TP</td></tr></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel-head"><div><h2>Baseline & Threshold</h2><small>Mean และ Sample SD คำนวณจากข้อมูล Normal; Threshold ตามนโยบายวิจัยถูกนำไปใช้จริง</small></div></div><div class="admin-table-wrap"><table><thead><tr><th>Behavior</th><th>Mean</th><th>SD</th><th>Threshold</th><th>Window</th><th>Samples</th></tr></thead><tbody><?php foreach($base as$b):?><tr><td><strong><?=e($b['feature_name_en'])?></strong><br><small><?=e($b['feature_name_th'])?></small></td><td><?=number_format($b['mean_value'],3)?></td><td><?=number_format($b['sd_value'],3)?></td><td><strong>&gt; <?=number_format($b['threshold_value'],2)?></strong></td><td><?=$b['window_seconds']?> sec</td><td><?=number_format($b['sample_count'])?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel-head"><h2>System Performance</h2></div><div class="admin-table-wrap"><table><tbody><tr><th>Response time avg / P95</th><td><?=number_format($run['avg_response_time_ms'],2)?> / <?=number_format($run['p95_response_time_ms'],2)?> ms</td><th>Detection time avg / P95</th><td><?=number_format($run['avg_detection_time_ms'],2)?> / <?=number_format($run['p95_detection_time_ms'],2)?> ms</td></tr><tr><th>Analysis throughput</th><td><?=number_format($run['throughput_cases_sec'],2)?> cases/sec</td><th>CPU usage / Peak memory</th><td><?=number_format($run['cpu_usage_percent'],2)?>% / <?=number_format($run['peak_memory_mb'],2)?> MB</td></tr></tbody></table></div></section>
<?php endif;include __DIR__.'/../includes/admin_footer.php';?>
