<?php
$page_title='ประวัติการส่งอีเมล';require_once __DIR__.'/../includes/auth_check.php';requireAdmin();require_once __DIR__.'/../config/database.php';$db=(new Database())->getConnection();
$message='';if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf(false);$id=(int)($_POST['id']??0);if(($_POST['action']??'')==='retry_all'){$changed=$db->exec("UPDATE email_delivery_logs SET status='queued',next_attempt_at=NOW(),locked_at=NULL,error_message=NULL WHERE status IN ('failed','dead')");auditLog($db,'email.retry_all','email_delivery_log',null,null,['count'=>$changed]);$message='นำอีเมลที่ล้มเหลวกลับเข้าคิวแล้ว '.$changed.' รายการ';}elseif($id>0){$stmt=$db->prepare("UPDATE email_delivery_logs SET status='queued',next_attempt_at=NOW(),locked_at=NULL,error_message=NULL WHERE id=? AND status IN ('failed','dead')");$stmt->execute([$id]);if($stmt->rowCount()){auditLog($db,'email.retry','email_delivery_log',$id);$message='นำอีเมลกลับเข้าคิวแล้ว';}}}
$status=(string)($_GET['status']??'');$allowed=['queued','sent','failed','sending','dead'];$where=in_array($status,$allowed,true)?' WHERE l.status=?':'';$stmt=$db->prepare('SELECT l.*,u.username FROM email_delivery_logs l LEFT JOIN users u ON u.id=l.user_id'.$where.' ORDER BY l.id DESC LIMIT 200');$stmt->execute($where?[$status]:[]);$rows=$stmt->fetchAll();
$counts=['queued'=>0,'sent'=>0,'failed'=>0,'sending'=>0,'dead'=>0];foreach($db->query('SELECT status,COUNT(*) total FROM email_delivery_logs GROUP BY status') as $row)$counts[$row['status']]=(int)$row['total'];require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">EMAIL DELIVERY</p><h1>ประวัติการส่งอีเมล</h1><p>ตรวจสอบอีเมลธุรกรรมที่ส่งสำเร็จ ล้มเหลว หรือกำลังดำเนินการ</p></div></header>
<?php if($message):?><div class="admin-alert success"><?php echo e($message);?></div><?php endif;?>
<form method="post" style="margin-bottom:16px"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><button class="btn btn-outline" name="action" value="retry_all"><i class="fa-solid fa-rotate"></i> ส่งอีเมลที่ล้มเหลวใหม่</button></form>
<section class="stat-grid"><a class="stat-card" href="?status=sent"><div><small>ส่งสำเร็จ</small><strong><?php echo $counts['sent'];?></strong></div><i class="fa-solid fa-envelope-circle-check"></i></a><a class="stat-card" href="?status=failed"><div><small>ส่งล้มเหลว</small><strong><?php echo $counts['failed'];?></strong></div><i class="fa-solid fa-triangle-exclamation"></i></a><a class="stat-card" href="?status=sending"><div><small>กำลังส่ง</small><strong><?php echo $counts['sending'];?></strong></div><i class="fa-solid fa-paper-plane"></i></a></section>
<section class="admin-panel"><div class="admin-toolbar"><strong>ล่าสุดไม่เกิน 200 รายการ</strong><?php if($status!==''):?><a class="btn btn-outline" href="email-logs.php">ดูทั้งหมด</a><?php endif;?></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เวลา</th><th>ผู้รับ</th><th>เหตุการณ์</th><th>หัวข้อ</th><th>สถานะ</th><th>ครั้งที่ลอง</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6" class="admin-empty">ยังไม่มีประวัติการส่งอีเมล</td></tr><?php endif;foreach($rows as $row):?><tr><td><?php echo e(date('d/m/Y H:i',strtotime($row['created_at'])));?></td><td><strong><?php echo e($row['username']?:'-');?></strong><small class="cell-subtitle"><?php echo e($row['recipient_email']);?></small></td><td><?php echo e($row['event_type']);?></td><td><?php echo e($row['subject']);?><?php if($row['error_message']):?><small class="cell-subtitle" style="color:#9a3730"><?php echo e($row['error_message']);?></small><?php endif;?></td><td><span class="status-badge <?php echo $row['status']==='sent'?'paid':($row['status']==='failed'?'cancelled':'pending');?>"><?php echo e($row['status']);?></span></td><td><?php echo (int)$row['attempts'];?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require_once __DIR__.'/../includes/admin_footer.php';?>
