<?php
$page_title='จัดการคำสั่งซื้อ';
require_once __DIR__.'/../includes/auth_check.php';
requireAdmin();
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../includes/commerce_workflow.php';
$db=(new Database())->getConnection();$message='';$error='';

if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='update_status'){
    requireCsrf(false);$orderId=(int)($_POST['order_id']??0);$paymentStatus=$_POST['payment_status']??'';$orderStatus=$_POST['order_status']??'';
    $validPayment=['pending','paid','cod_pending'];$validOrder=['pending','processing','shipped','completed','cancelled'];
    if($db&&$orderId>0&&in_array($paymentStatus,$validPayment,true)&&in_array($orderStatus,$validOrder,true)){
        try{$db->beginTransaction();$current=$db->prepare('SELECT id,order_status,payment_status,payment_method,user_id,order_no FROM orders WHERE id=? FOR UPDATE');$current->execute([$orderId]);$before=$current->fetch();if(!$before)throw new RuntimeException('ไม่พบคำสั่งซื้อ');assertOrderTransition($before,$orderStatus,$paymentStatus);if($orderStatus==='cancelled'&&$before['order_status']!=='cancelled'){cancelOrderAndRestock($db,$orderId);}else{$stmt=$db->prepare('UPDATE orders SET payment_status=?,order_status=? WHERE id=?');$stmt->execute([$paymentStatus,$orderStatus,$orderId]);}recordOrderHistory($db,$orderId,$orderStatus,$paymentStatus,'ผู้ดูแลอัปเดตสถานะ',(int)$_SESSION['user_id']);auditLog($db,'order.status.update','order',$orderId,$before,['order_status'=>$orderStatus,'payment_status'=>$paymentStatus]);createNotification($db,(int)$before['user_id'],'order','อัปเดตคำสั่งซื้อ '.$before['order_no'],'สถานะล่าสุด: '.adminStatusLabel($orderStatus),BASE_URL.'order-detail.php?id='.$orderId);$db->commit();$message=$orderStatus==='cancelled'?'ยกเลิกคำสั่งซื้อและคืนสต็อกแล้ว':'บันทึกสถานะคำสั่งซื้อแล้ว';}catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'ไม่สามารถบันทึกสถานะคำสั่งซื้อได้';}
    }else $error='ข้อมูลสถานะไม่ถูกต้อง';
}

$q=trim($_GET['q']??'');$orderFilter=$_GET['order_status']??'';$paymentFilter=$_GET['payment_status']??'';$methodFilter=$_GET['payment_method']??'';
if(!in_array($orderFilter,['','pending','processing','shipped','completed','cancelled'],true))$orderFilter='';
if(!in_array($paymentFilter,['','pending','paid','cod_pending'],true))$paymentFilter='';
if(!in_array($methodFilter,['','promptpay','cod'],true))$methodFilter='';
$orders=[];$totalOrders=0;$statusCounts=['pending'=>0,'processing'=>0,'shipped'=>0,'completed'=>0,'cancelled'=>0];
if($db){foreach($db->query('SELECT order_status,COUNT(*) count FROM orders GROUP BY order_status') as $row)$statusCounts[$row['order_status']]=(int)$row['count'];$where=' FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE 1=1';$params=[];if($q!==''){$where.=' AND (o.order_no LIKE ? OR o.shipping_name LIKE ? OR o.shipping_phone LIKE ? OR u.username LIKE ?)';for($i=0;$i<4;$i++)$params[]="%{$q}%";}if($orderFilter!==''){$where.=' AND o.order_status=?';$params[]=$orderFilter;}if($paymentFilter!==''){$where.=' AND o.payment_status=?';$params[]=$paymentFilter;}if($methodFilter!==''){$where.=' AND o.payment_method=?';$params[]=$methodFilter;}$count=$db->prepare('SELECT COUNT(*)'.$where);$count->execute($params);$totalOrders=(int)$count->fetchColumn();$stmt=$db->prepare('SELECT o.*,u.username,u.email'.$where.' ORDER BY o.id DESC');$stmt->execute($params);$orders=$stmt->fetchAll();}
require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">ORDER OPERATIONS</p><h1>คำสั่งซื้อ</h1><p>ค้นหา ตรวจสอบการชำระเงิน และอัปเดตการจัดส่ง</p></div><div class="admin-actions"><a href="<?php echo BASE_URL; ?>admin/index.php" class="btn btn-outline"><i class="fa-solid fa-chart-pie"></i> ภาพรวมร้าน</a></div></header>
<?php if($message): ?><div class="admin-alert success"><i class="fa-solid fa-circle-check"></i> <?php echo e($message); ?></div><?php endif; ?><?php if($error): ?><div class="admin-alert error"><i class="fa-solid fa-circle-exclamation"></i> <?php echo e($error); ?></div><?php endif; ?>

<section class="stat-grid"><a class="stat-card" href="?order_status=pending"><div><small>รอดำเนินการ</small><strong><?php echo $statusCounts['pending']; ?></strong></div><i class="fa-solid fa-clock"></i></a><a class="stat-card" href="?order_status=processing"><div><small>กำลังแพ็ก</small><strong><?php echo $statusCounts['processing']; ?></strong></div><i class="fa-solid fa-box"></i></a><a class="stat-card" href="?order_status=shipped"><div><small>จัดส่งแล้ว</small><strong><?php echo $statusCounts['shipped']; ?></strong></div><i class="fa-solid fa-truck-fast"></i></a><a class="stat-card" href="?order_status=completed"><div><small>สำเร็จ</small><strong><?php echo $statusCounts['completed']; ?></strong></div><i class="fa-solid fa-circle-check"></i></a></section>

<section class="admin-panel" style="margin-bottom:18px"><div class="admin-toolbar"><form method="GET" class="admin-filter-form"><input type="search" name="q" value="<?php echo e($q); ?>" placeholder="เลขออเดอร์ ชื่อลูกค้า หรือเบอร์โทร"><select name="order_status"><option value="">ทุกสถานะจัดส่ง</option><?php foreach(['pending','processing','shipped','completed','cancelled'] as $status): ?><option value="<?php echo $status; ?>" <?php echo $orderFilter===$status?'selected':''; ?>><?php echo e(adminStatusLabel($status)); ?></option><?php endforeach; ?></select><select name="payment_status"><option value="">ทุกสถานะชำระ</option><?php foreach(['pending','paid','cod_pending'] as $status): ?><option value="<?php echo $status; ?>" <?php echo $paymentFilter===$status?'selected':''; ?>><?php echo e(adminStatusLabel($status)); ?></option><?php endforeach; ?></select><select name="payment_method"><option value="">ทุกวิธีชำระ</option><option value="promptpay" <?php echo $methodFilter==='promptpay'?'selected':''; ?>>PromptPay</option><option value="cod" <?php echo $methodFilter==='cod'?'selected':''; ?>>เก็บเงินปลายทาง</option></select><button class="btn btn-primary"><i class="fa-solid fa-filter"></i> กรอง</button><?php if($q!==''||$orderFilter!==''||$paymentFilter!==''||$methodFilter!==''): ?><a class="btn btn-outline" href="<?php echo BASE_URL; ?>admin/orders.php">ล้าง</a><?php endif; ?></form><span class="result-count"><?php echo $totalOrders; ?> รายการ</span></div></section>

<div class="admin-order-list">
<?php if(!$orders): ?><div class="admin-panel admin-empty"><i class="fa-solid fa-clipboard-list"></i>ไม่พบคำสั่งซื้อที่ตรงกับตัวกรอง</div><?php endif; ?>
<?php foreach($orders as $order): ?><article class="admin-order-card"><form method="POST"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken()); ?>"><input type="hidden" name="action" value="update_status"><input type="hidden" name="order_id" value="<?php echo (int)$order['id']; ?>"><header class="admin-order-card-head"><div><strong><?php echo e($order['order_no']); ?></strong><span class="status-badge <?php echo e($order['order_status']); ?>"><?php echo e(adminStatusLabel($order['order_status'])); ?></span><time><i class="fa-regular fa-calendar"></i> <?php echo date('d/m/Y H:i',strtotime($order['created_at'])); ?></time></div><strong><?php echo formatCurrency($order['total_amount']); ?></strong></header><div class="admin-order-card-body"><div class="order-customer"><strong><?php echo e($order['shipping_name']); ?> · <?php echo e($order['shipping_phone']); ?></strong><p><?php echo e($order['shipping_address']); ?></p><small><i class="fa-solid <?php echo $order['payment_method']==='promptpay'?'fa-qrcode':'fa-truck-ramp-box'; ?>"></i> <?php echo $order['payment_method']==='promptpay'?'PromptPay':'เก็บเงินปลายทาง'; ?> · <?php echo e($order['email']??''); ?></small></div><div class="admin-field"><label>สถานะการชำระเงิน</label><select name="payment_status"><option value="pending" <?php echo $order['payment_status']==='pending'?'selected':''; ?>>รอชำระเงิน</option><option value="paid" <?php echo $order['payment_status']==='paid'?'selected':''; ?>>ชำระแล้ว</option><option value="cod_pending" <?php echo $order['payment_status']==='cod_pending'?'selected':''; ?>>รอเก็บเงิน COD</option></select></div><div class="admin-field"><label>สถานะคำสั่งซื้อ</label><select name="order_status" <?php echo $order['order_status']==='cancelled'?'disabled':''; ?>><option value="pending" <?php echo $order['order_status']==='pending'?'selected':''; ?>>รอดำเนินการ</option><option value="processing" <?php echo $order['order_status']==='processing'?'selected':''; ?>>กำลังแพ็ก</option><option value="shipped" <?php echo $order['order_status']==='shipped'?'selected':''; ?>>จัดส่งแล้ว</option><option value="completed" <?php echo $order['order_status']==='completed'?'selected':''; ?>>สำเร็จ</option><option value="cancelled" <?php echo $order['order_status']==='cancelled'?'selected':''; ?>>ยกเลิก</option></select><?php if($order['order_status']==='cancelled'): ?><input type="hidden" name="order_status" value="cancelled"><?php endif; ?></div><div class="order-card-actions"><a href="<?php echo BASE_URL; ?>admin/order-detail.php?id=<?php echo (int)$order['id']; ?>" class="btn btn-outline"><i class="fa-regular fa-eye"></i> รายละเอียด</a><button class="btn btn-primary" type="submit" <?php echo $order['order_status']==='cancelled'?'disabled':''; ?>><i class="fa-solid fa-floppy-disk"></i> บันทึก</button></div></div></form></article><?php endforeach; ?>
</div>
<?php require_once __DIR__.'/../includes/admin_footer.php'; ?>
