<?php
$page_title='คืนสินค้าและคืนเงิน';require_once __DIR__.'/../includes/auth_check.php';requireAdmin();require_once __DIR__.'/../config/database.php';
$db=(new Database())->getConnection();$message=$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 requireCsrf(false);$id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');$note=trim((string)($_POST['admin_note']??''));
 if(!in_array($action,['approve','reject','received','refund'],true))$error='คำสั่งไม่ถูกต้อง';else try{
  $db->beginTransaction();$stmt=$db->prepare('SELECT r.*,o.total_amount,o.payment_status,o.order_no,o.coupon_id FROM return_requests r JOIN orders o ON o.id=r.order_id WHERE r.id=? FOR UPDATE');$stmt->execute([$id]);$r=$stmt->fetch();if(!$r)throw new RuntimeException('ไม่พบคำขอ');
  $transitions=['requested'=>['approve'=>'approved','reject'=>'rejected'],'approved'=>['received'=>'received'],'received'=>['refund'=>'refunded']];
  if(!isset($transitions[$r['status']][$action]))throw new RuntimeException('ไม่สามารถเปลี่ยนจากสถานะ '.$r['status'].' ด้วยคำสั่งนี้ได้');
  $next=$transitions[$r['status']][$action];
  if($action==='refund'){
   if($r['status']!=='received')throw new RuntimeException('ต้องยืนยันว่าได้รับสินค้าคืนก่อน');
   $refundTotal=$db->prepare('SELECT COALESCE(SUM(refund_amount),0) FROM return_request_items WHERE return_request_id=?');$refundTotal->execute([$id]);$refundAmount=(float)$refundTotal->fetchColumn();if($refundAmount<=0)$refundAmount=(float)$r['total_amount'];
   $db->prepare("INSERT INTO refunds(order_id,return_request_id,amount,status,reason,processed_at) VALUES(?,?,?,'succeeded',?,NOW())")->execute([(int)$r['order_id'],$id,$refundAmount,$note?:'คืนเงินตามรายการที่อนุมัติ']);
   $items=$db->prepare('SELECT oi.product_id,oi.variant_id,COALESCE(ri.quantity,oi.quantity) quantity FROM order_items oi LEFT JOIN return_request_items ri ON ri.order_item_id=oi.id AND ri.return_request_id=? WHERE oi.order_id=? AND (ri.id IS NOT NULL OR NOT EXISTS(SELECT 1 FROM return_request_items x WHERE x.return_request_id=?))');$items->execute([$id,(int)$r['order_id'],$id]);$restore=$db->prepare('UPDATE products SET stock_quantity=stock_quantity+? WHERE id=?');$restoreVariant=$db->prepare('UPDATE product_variants SET stock_quantity=stock_quantity+? WHERE id=?');foreach($items->fetchAll() as $item){if(!empty($item['variant_id']))$restoreVariant->execute([(int)$item['quantity'],(int)$item['variant_id']]);else $restore->execute([(int)$item['quantity'],(int)$item['product_id']]);}
   $isFull=$refundAmount>=(float)$r['total_amount'];if($isFull&&!empty($r['coupon_id'])){$used=$db->prepare('DELETE FROM coupon_usages WHERE order_id=?');$used->execute([(int)$r['order_id']]);if($used->rowCount())$db->prepare('UPDATE user_coupons SET used_count=GREATEST(0,used_count-1) WHERE coupon_id=? AND user_id=?')->execute([(int)$r['coupon_id'],(int)$r['user_id']]);}
   $db->prepare("UPDATE orders SET payment_status=?,order_status=IF(?=1,'cancelled',order_status) WHERE id=?")->execute([$isFull?'refunded':'partially_refunded',$isFull?1:0,(int)$r['order_id']]);
  }
  $db->prepare('UPDATE return_requests SET status=?,admin_note=? WHERE id=?')->execute([$next,$note?:null,$id]);createNotification($db,(int)$r['user_id'],'return','อัปเดตคำขอคืนสินค้า','คำขอสำหรับ '.$r['order_no'].' เปลี่ยนเป็น '.$next,BASE_URL.'my-returns.php');$db->commit();$message='อัปเดตคำขอเรียบร้อย';
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}
}
$rows=$db->query('SELECT r.*,o.order_no,o.total_amount,u.username FROM return_requests r JOIN orders o ON o.id=r.order_id JOIN users u ON u.id=r.user_id ORDER BY r.id DESC')->fetchAll();require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">AFTER SALES</p><h1>คืนสินค้าและคืนเงิน</h1><p>ดำเนินการตามลำดับ: รอตรวจสอบ → อนุมัติ → รับสินค้าคืน → คืนเงิน</p></div></header><?php if($message):?><div class="admin-alert success"><?php echo e($message);?></div><?php endif;?><?php if($error):?><div class="admin-alert error"><?php echo e($error);?></div><?php endif;?><section class="admin-panel"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ออเดอร์</th><th>เหตุผล</th><th>สถานะ</th><th>ขั้นตอนถัดไป</th></tr></thead><tbody><?php foreach($rows as $r):$labels=['requested'=>'รอตรวจสอบ','approved'=>'อนุมัติแล้ว รอลูกค้าส่งคืน','rejected'=>'ปฏิเสธ','received'=>'ได้รับสินค้าคืนแล้ว','refunded'=>'คืนเงินแล้ว','cancelled'=>'ยกเลิก'];?><tr><td><strong><?php echo e($r['order_no']);?></strong><small class="cell-subtitle"><?php echo e($r['username']);?> · <?php echo formatCurrency($r['total_amount']);?></small></td><td><?php echo e($r['reason']);?><?php if($r['admin_note']):?><small class="cell-subtitle">หมายเหตุ: <?php echo e($r['admin_note']);?></small><?php endif;?></td><td><span class="status-badge <?php echo e($r['status']);?>"><?php echo e($labels[$r['status']]??$r['status']);?></span></td><td><?php if(in_array($r['status'],['requested','approved','received'],true)):?><form method="post" class="table-actions"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="id" value="<?php echo (int)$r['id'];?>"><input name="admin_note" maxlength="500" placeholder="หมายเหตุ"><?php if($r['status']==='requested'):?><button class="btn btn-primary" name="action" value="approve">อนุมัติคืนสินค้า</button><button class="btn btn-danger" name="action" value="reject">ปฏิเสธ</button><?php elseif($r['status']==='approved'):?><button class="btn btn-primary" name="action" value="received">ยืนยันว่าได้รับสินค้าคืน</button><?php elseif($r['status']==='received'):?><button class="btn btn-primary" name="action" value="refund">ยืนยันคืนเงิน</button><?php endif;?></form><?php else:?><small>ดำเนินการเสร็จแล้ว</small><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php require_once __DIR__.'/../includes/admin_footer.php';?>
