<?php
$page_title='ศูนย์ความปลอดภัย';require_once __DIR__.'/../includes/auth_check.php';requireAdmin();require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/security_monitor.php';$db=(new Database())->getConnection();$message=$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf(false);$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);try{if($action==='release'&&$id>0){$stmt=$db->prepare('UPDATE security_blocks SET is_active=0,released_at=NOW() WHERE id=? AND is_active=1');$stmt->execute([$id]);auditLog($db,'security.block.release','security_block',$id);$message=$stmt->rowCount()?'ปลดบล็อกเรียบร้อย':'รายการนี้ถูกปลดบล็อกแล้ว';}elseif($action==='block_user'){$userId=(int)($_POST['user_id']??0);$minutes=max(5,min(1440,(int)($_POST['minutes']??60)));if($userId<1)throw new RuntimeException('กรุณาระบุผู้ใช้');securityBlock($db,'user',hash('sha256','user:'.$userId),$userId,'ผู้ดูแลระงับชั่วคราว',80,$minutes*60,(int)$_SESSION['user_id']);auditLog($db,'security.block.manual','user',$userId,null,['minutes'=>$minutes]);$message='ระงับบัญชีชั่วคราวแล้ว';}else throw new RuntimeException('คำสั่งไม่ถูกต้อง');}catch(Throwable $e){$error=$e->getMessage();}}
$metrics=['today'=>0,'high'=>0,'blocked'=>0,'login'=>0];$metrics['today']=(int)$db->query('SELECT COUNT(*) FROM security_events WHERE created_at>=CURRENT_DATE()')->fetchColumn();$metrics['high']=(int)$db->query("SELECT COUNT(*) FROM security_events WHERE created_at>=CURRENT_DATE() AND severity IN ('high','critical')")->fetchColumn();$metrics['blocked']=(int)$db->query('SELECT COUNT(*) FROM security_blocks WHERE is_active=1 AND blocked_until>NOW()')->fetchColumn();$metrics['login']=(int)$db->query("SELECT COUNT(*) FROM security_events WHERE event_type='login.failed' AND created_at>=CURRENT_DATE()")->fetchColumn();
$events=$db->query('SELECT se.*,u.username FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 200')->fetchAll();$blocks=$db->query('SELECT sb.*,u.username FROM security_blocks sb LEFT JOIN users u ON u.id=sb.user_id WHERE sb.is_active=1 AND sb.blocked_until>NOW() ORDER BY sb.risk_score DESC,sb.id DESC')->fetchAll();require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">SECURITY CENTER</p><h1>ตรวจจับพฤติกรรมผิดปกติ</h1><p>ติดตามคะแนนความเสี่ยง การเข้าสู่ระบบผิด การเข้าถึงที่ไม่ได้รับอนุญาต และรายการระงับชั่วคราว</p></div></header>
<?php if($message):?><div class="admin-alert success"><?php echo e($message);?></div><?php endif;if($error):?><div class="admin-alert error"><?php echo e($error);?></div><?php endif;?>
<section class="stat-grid"><div class="stat-card"><div><small>เหตุการณ์วันนี้</small><strong><?php echo $metrics['today'];?></strong></div><i class="fa-solid fa-shield"></i></div><div class="stat-card"><div><small>ความเสี่ยงสูง</small><strong><?php echo $metrics['high'];?></strong></div><i class="fa-solid fa-triangle-exclamation"></i></div><div class="stat-card"><div><small>กำลังถูกบล็อก</small><strong><?php echo $metrics['blocked'];?></strong></div><i class="fa-solid fa-ban"></i></div><div class="stat-card"><div><small>Login ผิดวันนี้</small><strong><?php echo $metrics['login'];?></strong></div><i class="fa-solid fa-key"></i></div></section>
<section class="admin-panel" style="margin-bottom:18px"><header class="admin-panel-header"><div><h2>รายการระงับชั่วคราว</h2><p>ระบบจะปลดอัตโนมัติเมื่อครบกำหนด หรือผู้ดูแลสามารถปลดได้ทันที</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เป้าหมาย</th><th>เหตุผล</th><th>คะแนน</th><th>ถึงเวลา</th><th>จัดการ</th></tr></thead><tbody><?php if(!$blocks):?><tr><td colspan="5" class="admin-empty">ไม่มีรายการที่กำลังถูกระงับ</td></tr><?php endif;foreach($blocks as $block):?><tr><td><?php echo e($block['target_type']);?><small class="cell-subtitle"><?php echo e($block['username']?:substr($block['target_hash'],0,12).'…');?></small></td><td><?php echo e($block['reason']);?></td><td><strong><?php echo (int)$block['risk_score'];?>/100</strong></td><td><?php echo e(date('d/m/Y H:i',strtotime($block['blocked_until'])));?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="id" value="<?php echo (int)$block['id'];?>"><button class="btn btn-outline" name="action" value="release">ปลดบล็อก</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="admin-panel"><header class="admin-panel-header"><div><h2>เหตุการณ์ล่าสุด</h2><p>แสดงล่าสุดไม่เกิน 200 รายการ โดยไม่เก็บ IP จริง</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เวลา</th><th>เหตุการณ์</th><th>ผู้ใช้ / IP</th><th>คะแนน</th><th>การตอบสนอง</th></tr></thead><tbody><?php if(!$events):?><tr><td colspan="5" class="admin-empty">ยังไม่มีเหตุการณ์</td></tr><?php endif;foreach($events as $event):?><tr><td><?php echo e(date('d/m/Y H:i:s',strtotime($event['created_at'])));?></td><td><strong><?php echo e($event['event_type']);?></strong><small class="cell-subtitle"><?php echo e($event['request_method'].' '.$event['request_path']);?></small></td><td><?php echo e($event['username']?:'-');?><small class="cell-subtitle"><?php echo e($event['ip_masked']);?><?php echo $event['country_code']?' · '.e($event['country_code']):'';?></small></td><td><span class="status-badge <?php echo in_array($event['severity'],['high','critical'],true)?'cancelled':($event['severity']==='medium'?'pending':'paid');?>"><?php echo (int)$event['risk_score'];?> · <?php echo e($event['severity']);?></span></td><td><?php echo e($event['action_taken']);?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require_once __DIR__.'/../includes/admin_footer.php';?>
