<?php
$page_title='ศูนย์ความปลอดภัย';require_once __DIR__.'/../includes/auth_check.php';requireAdmin();require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/security_monitor.php';$db=(new Database())->getConnection();$message=$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf(false);$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);try{if($action==='release'&&$id>0){$stmt=$db->prepare('UPDATE security_blocks SET is_active=0,released_at=NOW() WHERE id=? AND is_active=1');$stmt->execute([$id]);auditLog($db,'security.block.release','security_block',$id);$message=$stmt->rowCount()?'ปลดบล็อกเรียบร้อย':'รายการนี้ถูกปลดบล็อกแล้ว';}elseif($action==='block_user'){$userId=(int)($_POST['user_id']??0);$minutes=max(5,min(1440,(int)($_POST['minutes']??60)));if($userId<1)throw new RuntimeException('กรุณาระบุผู้ใช้');securityBlock($db,'user',hash('sha256','user:'.$userId),$userId,'ผู้ดูแลระงับชั่วคราว',80,$minutes*60,(int)$_SESSION['user_id']);auditLog($db,'security.block.manual','user',$userId,null,['minutes'=>$minutes]);$message='ระงับบัญชีชั่วคราวแล้ว';}else throw new RuntimeException('คำสั่งไม่ถูกต้อง');}catch(Throwable $e){$error=$e->getMessage();}}
function securityAttemptNumber(array $event):?int{$meta=json_decode((string)($event['metadata_json']??''),true);if(!is_array($meta))return null;$value=$meta['attempt']??$meta['identity_failures']??null;return is_numeric($value)?(int)$value:null;}
function securitySpreadsheetCell($value):string{$value=(string)($value??'');return preg_match('/^[=+\-@]/u',$value)?"'".$value:$value;}
if(($_GET['export']??'')==='excel'){
    $exportLanguage=($_GET['lang']??'th')==='en'?'en':'th';
    $rows=$db->query("SELECT se.*,u.username FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 10000")->fetchAll();
    auditLog($db,'security.events.export','security_event',null,null,['rows'=>count($rows),'language'=>$exportLanguage]);
    $filename=$exportLanguage==='en'?'kitchenmart-security-analysis-en-':'kitchenmart-security-th-';
    header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.date('Ymd-His').'.csv"');header('Cache-Control: no-store');
    $output=fopen('php://output','wb');fwrite($output,"\xEF\xBB\xBF");
    if($exportLanguage==='en'){
        fputcsv($output,['event_id','timestamp_iso_8601','event_type','user_id','username','masked_ip','country_code','failed_attempt_number','risk_score','severity','action_taken','request_method','request_path','metadata_json']);
        foreach($rows as $row)fputcsv($output,array_map('securitySpreadsheetCell',[(int)$row['id'],date(DATE_ATOM,strtotime($row['created_at'])),$row['event_type'],$row['user_id']?:'',$row['username']?:'unknown',$row['ip_masked'],$row['country_code']?:'',securityAttemptNumber($row)??'',(int)$row['risk_score'],$row['severity'],$row['action_taken'],$row['request_method'],$row['request_path'],$row['metadata_json']?:'']));
    }else{
        fputcsv($output,['เวลา','เหตุการณ์','ผู้ใช้','IP แบบปกปิด','ประเทศ','ผิดครั้งที่','คะแนนความเสี่ยง','ระดับ','การตอบสนอง','Method','Path']);
        foreach($rows as $row)fputcsv($output,array_map('securitySpreadsheetCell',[date('d/m/Y H:i:s',strtotime($row['created_at'])),$row['event_type'],$row['username']?:'-',$row['ip_masked'],$row['country_code']?:'-',securityAttemptNumber($row)??'-',(int)$row['risk_score'],$row['severity'],$row['action_taken'],$row['request_method'],$row['request_path']]));
    }
    fclose($output);exit;
}
$metrics=['today'=>0,'high'=>0,'blocked'=>0,'login'=>0];$metrics['today']=(int)$db->query('SELECT COUNT(*) FROM security_events WHERE created_at>=CURRENT_DATE()')->fetchColumn();$metrics['high']=(int)$db->query("SELECT COUNT(*) FROM security_events WHERE created_at>=CURRENT_DATE() AND severity IN ('high','critical')")->fetchColumn();$metrics['blocked']=(int)$db->query('SELECT COUNT(*) FROM security_blocks WHERE is_active=1 AND blocked_until>NOW()')->fetchColumn();$metrics['login']=(int)$db->query("SELECT COUNT(*) FROM security_events WHERE event_type='login.failed' AND created_at>=CURRENT_DATE()")->fetchColumn();
$loginSummary=$db->query("SELECT MAX(se.user_id) user_id,MAX(u.username) username,MAX(se.ip_masked) ip_masked,COUNT(*) failures_30d,SUM(se.created_at>=CURRENT_DATE()) failures_today,SUM(se.created_at>DATE_SUB(NOW(),INTERVAL 15 MINUTE)) failures_15m,MAX(se.created_at) last_failed_at FROM security_events se LEFT JOIN users u ON u.id=se.user_id WHERE se.event_type='login.failed' AND se.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY COALESCE(JSON_UNQUOTE(JSON_EXTRACT(se.metadata_json,'$.identifier_hash')),CONCAT('ip:',se.ip_hash)) ORDER BY last_failed_at DESC LIMIT 100")->fetchAll();
$events=$db->query('SELECT se.*,u.username FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 200')->fetchAll();$blocks=$db->query('SELECT sb.*,u.username FROM security_blocks sb LEFT JOIN users u ON u.id=sb.user_id WHERE sb.is_active=1 AND sb.blocked_until>NOW() ORDER BY sb.risk_score DESC,sb.id DESC')->fetchAll();require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">SECURITY CENTER</p><h1>ตรวจจับพฤติกรรมผิดปกติ</h1><p>ติดตามคะแนนความเสี่ยง การเข้าสู่ระบบผิด การเข้าถึงที่ไม่ได้รับอนุญาต และรายการระงับชั่วคราว</p></div><div class="admin-actions"><a class="btn btn-outline" href="?export=excel&amp;lang=th"><i class="fa-solid fa-file-excel"></i> Excel ภาษาไทย</a><a class="btn btn-primary" href="?export=excel&amp;lang=en"><i class="fa-solid fa-chart-line"></i> English Analysis</a></div></header>
<?php if($message):?><div class="admin-alert success"><?php echo e($message);?></div><?php endif;if($error):?><div class="admin-alert error"><?php echo e($error);?></div><?php endif;?>
<section class="stat-grid"><div class="stat-card"><div><small>เหตุการณ์วันนี้</small><strong><?php echo $metrics['today'];?></strong></div><i class="fa-solid fa-shield"></i></div><div class="stat-card"><div><small>ความเสี่ยงสูง</small><strong><?php echo $metrics['high'];?></strong></div><i class="fa-solid fa-triangle-exclamation"></i></div><div class="stat-card"><div><small>กำลังถูกบล็อก</small><strong><?php echo $metrics['blocked'];?></strong></div><i class="fa-solid fa-ban"></i></div><div class="stat-card"><div><small>Login ผิดวันนี้</small><strong><?php echo $metrics['login'];?></strong></div><i class="fa-solid fa-key"></i></div></section>
<section class="admin-panel" style="margin-bottom:18px"><header class="admin-panel-header"><div><h2>สรุปจำนวนรหัสผ่านผิด</h2><p>นับแยกตามชื่อผู้ใช้ในช่วง 15 นาที วันนี้ และย้อนหลัง 30 วัน</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ผู้ใช้ / IP</th><th>15 นาทีล่าสุด</th><th>วันนี้</th><th>30 วัน</th><th>สถานะ</th><th>ผิดล่าสุด</th></tr></thead><tbody><?php if(!$loginSummary):?><tr><td colspan="6" class="admin-empty">ยังไม่มีการเข้าสู่ระบบผิด</td></tr><?php endif;foreach($loginSummary as $summary):$recent=(int)$summary['failures_15m'];?><tr><td><strong><?php echo e($summary['username']?:'ไม่ทราบชื่อผู้ใช้');?></strong><small class="cell-subtitle"><?php echo e($summary['ip_masked']?:'-');?></small></td><td><strong><?php echo $recent;?> ครั้ง</strong></td><td><?php echo (int)$summary['failures_today'];?> ครั้ง</td><td><?php echo (int)$summary['failures_30d'];?> ครั้ง</td><td><span class="status-badge <?php echo $recent>=10?'cancelled':($recent>=5?'pending':'paid');?>"><?php echo $recent>=10?'พักชั่วคราว':($recent>=5?'ส่งคำเตือนแล้ว':'เฝ้าระวัง');?></span></td><td><?php echo e(date('d/m/Y H:i:s',strtotime($summary['last_failed_at'])));?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="admin-panel" style="margin-bottom:18px"><header class="admin-panel-header"><div><h2>รายการระงับชั่วคราว</h2><p>ระบบจะปลดอัตโนมัติเมื่อครบกำหนด หรือผู้ดูแลสามารถปลดได้ทันที</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เป้าหมาย</th><th>เหตุผล</th><th>คะแนน</th><th>ถึงเวลา</th><th>จัดการ</th></tr></thead><tbody><?php if(!$blocks):?><tr><td colspan="5" class="admin-empty">ไม่มีรายการที่กำลังถูกระงับ</td></tr><?php endif;foreach($blocks as $block):?><tr><td><?php echo e($block['target_type']);?><small class="cell-subtitle"><?php echo e($block['username']?:substr($block['target_hash'],0,12).'…');?></small></td><td><?php echo e($block['reason']);?></td><td><strong><?php echo (int)$block['risk_score'];?>/100</strong></td><td><?php echo e(date('d/m/Y H:i',strtotime($block['blocked_until'])));?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="id" value="<?php echo (int)$block['id'];?>"><button class="btn btn-outline" name="action" value="release">ปลดบล็อก</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="admin-panel"><header class="admin-panel-header"><div><h2>เหตุการณ์ล่าสุด</h2><p>แสดงล่าสุดไม่เกิน 200 รายการ โดยไม่เก็บ IP จริง</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เวลา</th><th>เหตุการณ์</th><th>ผู้ใช้ / IP</th><th>ผิดครั้งที่</th><th>คะแนน</th><th>การตอบสนอง</th></tr></thead><tbody><?php if(!$events):?><tr><td colspan="6" class="admin-empty">ยังไม่มีเหตุการณ์</td></tr><?php endif;foreach($events as $event):$attemptNo=securityAttemptNumber($event);?><tr><td><?php echo e(date('d/m/Y H:i:s',strtotime($event['created_at'])));?></td><td><strong><?php echo e($event['event_type']);?></strong><small class="cell-subtitle"><?php echo e($event['request_method'].' '.$event['request_path']);?></small></td><td><?php echo e($event['username']?:'-');?><small class="cell-subtitle"><?php echo e($event['ip_masked']);?><?php echo $event['country_code']?' · '.e($event['country_code']):'';?></small></td><td><?php echo $attemptNo!==null?'<strong>'.(int)$attemptNo.' ครั้ง</strong>':'-';?></td><td><span class="status-badge <?php echo in_array($event['severity'],['high','critical'],true)?'cancelled':($event['severity']==='medium'?'pending':'paid');?>"><?php echo (int)$event['risk_score'];?> · <?php echo e($event['severity']);?></span></td><td><?php echo e($event['action_taken']);?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require_once __DIR__.'/../includes/admin_footer.php';?>
