<?php
$page_title='ตรวจสินค้าผู้ขาย';
require_once __DIR__.'/../includes/auth_check.php';requireAdmin();require_once __DIR__.'/../config/database.php';
$db=(new Database())->getConnection();$message=$error='';
if(($_GET['updated']??'')==='approved')$message='อนุมัติสินค้าและแจ้งผู้ขายเรียบร้อยแล้ว';
if(($_GET['updated']??'')==='rejected')$message='ปฏิเสธสินค้าและแจ้งเหตุผลให้ผู้ขายแล้ว';
if($_SERVER['REQUEST_METHOD']==='POST'){
 requireCsrf(false);$id=(int)($_POST['product_id']??0);$action=(string)($_POST['action']??'');$note=trim((string)($_POST['admin_note']??''));
 try{
  if(!$db||$id<1||!in_array($action,['approve','reject'],true))throw new RuntimeException('ข้อมูลคำขอไม่ถูกต้อง');
  if($action==='reject'&&mb_strlen($note)<5)throw new RuntimeException('กรุณาระบุเหตุผลที่ปฏิเสธอย่างน้อย 5 ตัวอักษร');
  $db->beginTransaction();$find=$db->prepare("SELECT id,seller_id,name,approval_status,admin_note FROM products WHERE id=? AND seller_id IS NOT NULL FOR UPDATE");$find->execute([$id]);$product=$find->fetch();
  if(!$product)throw new RuntimeException('ไม่พบสินค้าผู้ขาย');if($product['approval_status']!=='pending')throw new RuntimeException('สินค้านี้ถูกตรวจสอบไปแล้ว กรุณารีเฟรชหน้า');
  $status=$action==='approve'?'approved':'rejected';$adminNote=$note!==''?$note:($action==='approve'?'ตรวจสอบข้อมูลสินค้าแล้ว':'');
  $update=$db->prepare("UPDATE products SET approval_status=?,admin_note=? WHERE id=? AND approval_status='pending'");$update->execute([$status,$adminNote,$id]);if($update->rowCount()!==1)throw new RuntimeException('สถานะสินค้าถูกเปลี่ยนไปแล้ว');
  auditLog($db,'seller_product.'.$status,'product',$id,['approval_status'=>$product['approval_status'],'admin_note'=>$product['admin_note']],['approval_status'=>$status,'admin_note'=>$adminNote]);
  createNotification($db,(int)$product['seller_id'],'seller',$action==='approve'?'สินค้าได้รับอนุมัติแล้ว':'สินค้ายังไม่ผ่านการอนุมัติ',$product['name'].' — '.$adminNote,BASE_URL.'my-store.php');
  $db->commit();header('Location: '.BASE_URL.'admin/seller-products.php?id='.$id.'&updated='.$status);exit;
 }catch(Throwable $e){if($db&&$db->inTransaction())$db->rollBack();$error=$e->getMessage();}
}
$statusFilter=(string)($_GET['status']??'');if(!in_array($statusFilter,['pending','approved','rejected'],true))$statusFilter='';$q=trim((string)($_GET['q']??''));
$where=['p.seller_id IS NOT NULL'];$params=[];if($statusFilter!==''){$where[]='p.approval_status=?';$params[]=$statusFilter;}if($q!==''){$where[]='(p.name LIKE ? OR u.username LIKE ? OR u.full_name LIKE ? OR sp.shop_name LIKE ?)';$term='%'.$q.'%';array_push($params,$term,$term,$term,$term);}
$list=$db->prepare('SELECT p.*,u.username,u.full_name,c.name category_name,sp.shop_name FROM products p JOIN users u ON u.id=p.seller_id LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN seller_profiles sp ON sp.user_id=p.seller_id WHERE '.implode(' AND ',$where).' ORDER BY FIELD(p.approval_status,"pending","approved","rejected"),p.created_at DESC');$list->execute($params);$products=$list->fetchAll();
$counts=['pending'=>0,'approved'=>0,'rejected'=>0];foreach($db->query("SELECT approval_status,COUNT(*) total FROM products WHERE seller_id IS NOT NULL GROUP BY approval_status") as $row)$counts[$row['approval_status']]=(int)$row['total'];
$selectedId=(int)($_GET['id']??0);$selected=null;$images=$variants=$history=[];$sales=['orders'=>0,'units'=>0,'revenue'=>0];$reviewStats=['reviews'=>0,'rating'=>0];
if($selectedId>0){
 $detail=$db->prepare('SELECT p.*,c.name category_name,u.username,u.full_name,u.email,u.phone user_phone,sp.shop_name,sp.shop_description,sp.shop_logo,sp.status shop_status,sp.phone shop_phone FROM products p JOIN users u ON u.id=p.seller_id LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN seller_profiles sp ON sp.user_id=p.seller_id WHERE p.id=? AND p.seller_id IS NOT NULL LIMIT 1');$detail->execute([$selectedId]);$selected=$detail->fetch();
 if(!$selected)$error='ไม่พบรายละเอียดสินค้าผู้ขายที่เลือก';else{
  $stmt=$db->prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY sort_order,id');$stmt->execute([$selectedId]);$images=$stmt->fetchAll();
  $stmt=$db->prepare('SELECT * FROM product_variants WHERE product_id=? ORDER BY is_active DESC,id');$stmt->execute([$selectedId]);$variants=$stmt->fetchAll();
  $stmt=$db->prepare("SELECT COUNT(DISTINCT oi.order_id) orders,COALESCE(SUM(oi.quantity),0) units,COALESCE(SUM(oi.subtotal),0) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=? AND o.order_status<>'cancelled'");$stmt->execute([$selectedId]);$sales=$stmt->fetch();
  $stmt=$db->prepare('SELECT COUNT(*) reviews,COALESCE(AVG(rating),0) rating FROM product_reviews WHERE product_id=?');$stmt->execute([$selectedId]);$reviewStats=$stmt->fetch();
  $stmt=$db->prepare("SELECT a.*,u.username actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id WHERE a.entity_type='product' AND a.entity_id=? AND a.action LIKE 'seller_product.%' ORDER BY a.id DESC LIMIT 20");$stmt->execute([(string)$selectedId]);$history=$stmt->fetchAll();
 }
}
$labels=['pending'=>'รอตรวจสอบ','approved'=>'อนุมัติแล้ว','rejected'=>'ปฏิเสธ'];require_once __DIR__.'/../includes/admin_header.php';
?>
<header class="admin-page-header"><div><p class="eyebrow">SELLER PRODUCTS</p><h1>ตรวจสินค้าผู้ขาย</h1><p>ตรวจข้อมูลสินค้า ผู้ขาย รูปภาพ ตัวเลือก และสต็อกก่อนเผยแพร่หน้าร้าน</p></div></header>
<?php if($message):?><div class="admin-alert success"><?php echo e($message);?></div><?php endif;if($error):?><div class="admin-alert error"><?php echo e($error);?></div><?php endif;?>
<section class="stat-grid"><a class="stat-card" href="?status=pending"><div><small>รอตรวจสอบ</small><strong><?php echo $counts['pending'];?></strong></div><i class="fa-solid fa-clock"></i></a><a class="stat-card" href="?status=approved"><div><small>อนุมัติแล้ว</small><strong><?php echo $counts['approved'];?></strong></div><i class="fa-solid fa-circle-check"></i></a><a class="stat-card" href="?status=rejected"><div><small>ปฏิเสธ</small><strong><?php echo $counts['rejected'];?></strong></div><i class="fa-solid fa-circle-xmark"></i></a><a class="stat-card" href="seller-products.php"><div><small>สินค้าผู้ขายทั้งหมด</small><strong><?php echo array_sum($counts);?></strong></div><i class="fa-solid fa-boxes-stacked"></i></a></section>
<?php if($selected):?>
<section class="admin-panel" style="margin-bottom:20px"><header class="admin-panel-header"><div><h2>รายละเอียดสินค้า #<?php echo (int)$selected['id'];?></h2><p>ส่งเมื่อ <?php echo e(date('d/m/Y H:i',strtotime($selected['created_at'])));?> · แก้ไขล่าสุด <?php echo e(date('d/m/Y H:i',strtotime($selected['updated_at'])));?></p></div><div class="admin-actions"><a class="btn btn-outline" href="seller-products.php"><i class="fa-solid fa-arrow-left"></i> กลับรายการ</a><?php if($selected['approval_status']==='approved'):?><a class="btn btn-primary" target="_blank" rel="noopener" href="<?php echo BASE_URL;?>product-detail.php?id=<?php echo (int)$selected['id'];?>">ดูหน้าสินค้า</a><?php endif;?></div></header>
 <div class="admin-detail-grid" style="padding:18px"><div style="display:grid;gap:18px">
  <article class="admin-detail-card"><div class="seller-review-product"><img src="<?php echo e(productImageUrl($selected['image_url']));?>" alt="<?php echo e($selected['name']);?>"><div><span class="status-badge <?php echo $selected['approval_status']==='approved'?'paid':($selected['approval_status']==='rejected'?'cancelled':'pending');?>"><?php echo e($labels[$selected['approval_status']]);?></span><p class="eyebrow" style="margin-top:18px"><?php echo e($selected['category_name']?:'ไม่ระบุหมวด');?></p><h2 class="seller-review-title"><?php echo e($selected['name']);?></h2><div class="detail-line"><span>ราคา</span><strong><?php echo formatCurrency($selected['price']);?></strong></div><div class="detail-line"><span>สต็อกหลัก</span><strong><?php echo (int)$selected['stock_quantity'];?> ชิ้น</strong></div><div class="detail-line"><span>สินค้าแนะนำ</span><strong><?php echo $selected['is_featured']?'ใช่':'ไม่ใช่';?></strong></div></div></div><?php if($images):?><div class="seller-review-gallery"><?php foreach($images as $image):?><img src="<?php echo e(productImageUrl($image['image_url']));?>" alt=""><?php endforeach;?></div><?php endif;?></article>
  <article class="admin-detail-card"><h2>รายละเอียดสินค้า</h2><p style="white-space:pre-line;line-height:1.8;color:var(--muted)"><?php echo e($selected['description']?:'ผู้ขายยังไม่ได้ระบุรายละเอียดสินค้า');?></p></article>
  <article class="admin-detail-card"><h2>ตัวเลือกสินค้าและ SKU</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>SKU</th><th>ชื่อตัวเลือก</th><th>ราคา</th><th>สต็อก</th><th>สถานะ</th></tr></thead><tbody><?php if(!$variants):?><tr><td colspan="5" class="admin-empty">สินค้านี้ไม่มีตัวเลือกเพิ่มเติม</td></tr><?php endif;foreach($variants as $variant):?><tr><td><strong><?php echo e($variant['sku']);?></strong></td><td><?php echo e($variant['name']);?></td><td><?php echo formatCurrency($variant['price']);?></td><td><?php echo (int)$variant['stock_quantity'];?> ชิ้น</td><td><span class="status-badge <?php echo $variant['is_active']?'paid':'cancelled';?>"><?php echo $variant['is_active']?'เปิดขาย':'ปิด';?></span></td></tr><?php endforeach;?></tbody></table></div></article>
  <article class="admin-detail-card"><h2>ประวัติการตรวจสอบ</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>เวลา</th><th>รายการ</th><th>ผู้ดำเนินการ</th></tr></thead><tbody><?php if(!$history):?><tr><td colspan="3" class="admin-empty">ยังไม่มีประวัติการตรวจ</td></tr><?php endif;foreach($history as $entry):?><tr><td><?php echo e(date('d/m/Y H:i',strtotime($entry['created_at'])));?></td><td><?php echo e($entry['action']);?></td><td><?php echo e($entry['actor_name']?:'ระบบ');?></td></tr><?php endforeach;?></tbody></table></div></article>
 </div><aside style="display:grid;gap:18px;align-content:start">
  <article class="admin-detail-card"><h2>ภาพรวมผลงาน</h2><div class="detail-line"><span>คำสั่งซื้อ</span><strong><?php echo (int)$sales['orders'];?></strong></div><div class="detail-line"><span>ขายแล้ว</span><strong><?php echo (int)$sales['units'];?> ชิ้น</strong></div><div class="detail-line"><span>ยอดขาย</span><strong><?php echo formatCurrency($sales['revenue']);?></strong></div><div class="detail-line"><span>รีวิว</span><strong><?php echo (int)$reviewStats['reviews'];?> รายการ</strong></div><div class="detail-line"><span>คะแนนเฉลี่ย</span><strong><?php echo number_format((float)$reviewStats['rating'],1);?> / 5</strong></div></article>
  <article class="admin-detail-card"><h2>ร้านค้าและผู้ขาย</h2><?php if($selected['shop_logo']):?><img src="<?php echo e(productImageUrl($selected['shop_logo']));?>" alt="" class="seller-review-logo"><?php endif;?><div class="detail-line"><span>ร้าน</span><strong><?php echo e($selected['shop_name']?:'-');?></strong></div><div class="detail-line"><span>สถานะร้าน</span><strong><?php echo e($selected['shop_status']?:'-');?></strong></div><div class="detail-line"><span>เจ้าของ</span><strong><?php echo e($selected['full_name']?:$selected['username']);?></strong></div><div class="detail-line"><span>Username</span><strong><?php echo e($selected['username']);?></strong></div><div class="detail-line"><span>อีเมล</span><strong><?php echo e($selected['email']);?></strong></div><div class="detail-line"><span>โทรศัพท์</span><strong><?php echo e($selected['shop_phone']?:$selected['user_phone']?:'-');?></strong></div><?php if($selected['shop_description']):?><p style="margin-top:14px;color:var(--muted);line-height:1.7"><?php echo e($selected['shop_description']);?></p><?php endif;?><a class="btn btn-outline" style="margin-top:14px;width:100%" href="sellers.php">ดูข้อมูลผู้ขายทั้งหมด</a></article>
  <article class="admin-detail-card"><h2>ผลการตรวจสินค้า</h2><?php if($selected['approval_status']==='pending'):?><form method="post" class="seller-review-form"><input type="hidden" name="csrf_token" value="<?php echo e(getCsrfToken());?>"><input type="hidden" name="product_id" value="<?php echo (int)$selected['id'];?>"><label>หมายเหตุถึงผู้ขาย<textarea name="admin_note" maxlength="500" rows="5" placeholder="ระบุสิ่งที่ตรวจพบ หรือเหตุผลหากปฏิเสธ"></textarea></label><button class="btn btn-primary" name="action" value="approve">อนุมัติสินค้า</button><button class="btn btn-danger" name="action" value="reject" onclick="return confirm('ยืนยันปฏิเสธสินค้านี้?')">ปฏิเสธพร้อมแจ้งเหตุผล</button></form><?php else:?><span class="status-badge <?php echo $selected['approval_status']==='approved'?'paid':'cancelled';?>"><?php echo e($labels[$selected['approval_status']]);?></span><p style="margin-top:12px;line-height:1.7"><?php echo e($selected['admin_note']?:'ไม่มีหมายเหตุ');?></p><?php endif;?></article>
 </aside></div>
</section>
<?php endif;?>
<section class="admin-panel"><div class="admin-toolbar"><form method="get" class="admin-filter-form"><input type="search" name="q" value="<?php echo e($q);?>" placeholder="ค้นหาสินค้า ร้าน หรือผู้ขาย"><select name="status"><option value="">ทุกสถานะ</option><?php foreach($labels as $key=>$label):?><option value="<?php echo $key;?>" <?php echo $statusFilter===$key?'selected':'';?>><?php echo e($label);?></option><?php endforeach;?></select><button class="btn btn-primary">กรอง</button><?php if($q!==''||$statusFilter!==''):?><a class="btn btn-outline" href="seller-products.php">ล้าง</a><?php endif;?></form><span class="result-count"><?php echo count($products);?> รายการ</span></div>
 <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>สินค้า</th><th>ร้าน / ผู้ขาย</th><th>ราคา / สต็อก</th><th>ส่งตรวจ</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody><?php if(!$products):?><tr><td colspan="6" class="admin-empty"><i class="fa-solid fa-box-open"></i>ยังไม่มีสินค้าจากผู้ขายในเงื่อนไขนี้</td></tr><?php endif;foreach($products as $product):?><tr><td><div class="seller-product-cell"><img class="admin-thumb" src="<?php echo e(productImageUrl($product['image_url']));?>" alt=""><div><span class="cell-title"><?php echo e($product['name']);?></span><span class="cell-subtitle"><?php echo e($product['category_name']?:'ไม่ระบุหมวด');?></span></div></div></td><td><strong><?php echo e($product['shop_name']?:$product['full_name']?:$product['username']);?></strong><span class="cell-subtitle"><?php echo e($product['username']);?></span></td><td><strong><?php echo formatCurrency($product['price']);?></strong><span class="cell-subtitle"><?php echo (int)$product['stock_quantity'];?> ชิ้น</span></td><td><?php echo e(date('d/m/Y H:i',strtotime($product['created_at'])));?></td><td><span class="status-badge <?php echo $product['approval_status']==='approved'?'paid':($product['approval_status']==='rejected'?'cancelled':'pending');?>"><?php echo e($labels[$product['approval_status']]);?></span></td><td><div class="table-actions"><a class="btn btn-outline" href="?id=<?php echo (int)$product['id'];?><?php echo $statusFilter!==''?'&amp;status='.e($statusFilter):'';?>"><i class="fa-regular fa-eye"></i> ดูรายละเอียด</a></div></td></tr><?php endforeach;?></tbody></table></div>
</section>
<?php require_once __DIR__.'/../includes/admin_footer.php';?>
