<?php
function chatbotOpenAI(array $messages,string $context):?string{
 $key=appConfig('OPENAI_API_KEY','');if($key==='')return null;$model=appConfig('OPENAI_MODEL','gpt-5');
 $history=[];foreach(array_slice($messages,-8) as $item)$history[]=['role'=>$item['sender']==='bot'?'assistant':'user','content'=>mb_substr($item['message'],0,1500)];
 $payload=['model'=>$model,'instructions'=>'คุณคือผู้ช่วยร้าน KitchenMart ตอบภาษาไทย กระชับ สุภาพ ใช้เฉพาะข้อมูลบริบทที่ให้ ห้ามสร้างราคา สต็อก สถานะคำสั่งซื้อ หรือนโยบายขึ้นเอง ถ้าไม่มีข้อมูลให้บอกว่าไม่แน่ใจและเสนอส่งต่อเจ้าหน้าที่ ห้ามขอรหัสผ่าน OTP เลขบัตร หรือ API key','input'=>array_merge([['role'=>'developer','content'=>'ข้อมูลจริงจากระบบ ณ ขณะตอบ:' . "\n".$context]],$history),'max_output_tokens'=>500];
 $ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($code<200||$code>=300||!is_string($raw))return null;$json=json_decode($raw,true);if(!is_array($json))return null;if(!empty($json['output_text']))return trim((string)$json['output_text']);foreach($json['output']??[] as $out)foreach($out['content']??[] as $content)if(($content['type']??'')==='output_text')return trim((string)($content['text']??''));return null;
}
function chatbotContext(PDO $db,string $message):array{
 $lines=['ชื่อร้าน: '.APP_NAME,'จัดส่งฟรีเมื่อยอดครบ 1,000 บาท','ช่องทางชำระเงิน: PromptPay QR และเก็บเงินปลายทาง','คืนสินค้าได้ภายใน 7 วันหลังได้รับสินค้า'];$products=[];
 $words=array_values(array_filter(preg_split('/\s+/u',preg_replace('/[^\p{L}\p{N}\s]/u',' ',$message)),fn($w)=>mb_strlen($w)>=2));if($words){$where=[];$params=[];foreach(array_slice($words,0,5) as $word){$where[]='(p.name LIKE ? OR p.description LIKE ? OR c.name LIKE ?)';array_push($params,"%$word%","%$word%","%$word%");}$stmt=$db->prepare("SELECT p.id,p.name,p.price,p.stock_quantity,p.image_url,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.approval_status='approved' AND (".implode(' OR ',$where).") ORDER BY p.is_featured DESC,p.id DESC LIMIT 5");$stmt->execute($params);$products=$stmt->fetchAll();}
 if(!$products&&preg_match('/แนะนำ|ขายดี|ยอดนิยม|น่าสนใจ/u',$message)){$sql="SELECT p.id,p.name,p.price,p.stock_quantity,p.image_url,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.approval_status='approved' AND p.stock_quantity>0";$params=[];if(preg_match('/(?:งบ|ไม่เกิน|ต่ำกว่า)\s*([0-9,]+)/u',$message,$match)){$sql.=' AND p.price<=?';$params[]=(float)str_replace(',','',$match[1]);}$sql.=' ORDER BY p.is_featured DESC,p.id DESC LIMIT 5';$stmt=$db->prepare($sql);$stmt->execute($params);$products=$stmt->fetchAll();}
 foreach($products as $p)$lines[]='สินค้า #'.$p['id'].' '.$p['name'].' ราคา '.formatCurrency($p['price']).' คงเหลือ '.(int)$p['stock_quantity'].' ชิ้น หมวด '.($p['category_name']??'-');
 if(isLoggedIn()&&preg_match('/ออเดอร์|คำสั่งซื้อ|พัสดุ|จัดส่ง|ชำระ/u',$message)){$stmt=$db->prepare('SELECT order_no,total_amount,payment_status,order_status FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 3');$stmt->execute([(int)$_SESSION['user_id']]);foreach($stmt->fetchAll() as $o)$lines[]='คำสั่งซื้อของผู้ใช้ '.$o['order_no'].' ยอด '.formatCurrency($o['total_amount']).' ชำระ='.$o['payment_status'].' สถานะ='.$o['order_status'];}
 return ['text'=>implode("\n",$lines),'products'=>$products];
}
