<?php
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once __DIR__.'/../config/database.php';
$db=(new Database())->getConnection();if(!$db){fwrite(STDERR,"Database unavailable\n");exit(1);}
$shop='Rorm888';$q=$db->prepare('SELECT sp.user_id,sp.shop_name FROM seller_profiles sp JOIN users u ON u.id=sp.user_id WHERE LOWER(sp.shop_name)=LOWER(?) OR LOWER(u.username)=LOWER(?) LIMIT 1');$q->execute([$shop,$shop]);$seller=$q->fetch();if(!$seller){fwrite(STDERR,"Store Rorm888 not found\n");exit(2);}
$catalog=[
 'pots-pans'=>[['กระทะเคลือบหินอ่อน 28 ซม.','frying-pan'],['หม้อสเตนเลสพร้อมฝา 24 ซม.','cooking-pot'],['หม้อด้ามอเนกประสงค์ 18 ซม.','saucepan'],['กระทะย่างทรงเหลี่ยม','grill-pan'],['ชุดหม้อทำอาหาร 5 ชิ้น','cookware']],
 'knives-boards'=>[['มีดเชฟสเตนเลส 8 นิ้ว','chef-knife'],['เขียงไม้ไผ่สองด้าน','cutting-board'],['ชุดมีดทำครัว 6 ชิ้น','kitchen-knives'],['มีดปอกผลไม้ด้ามจับนุ่ม','paring-knife'],['ที่ลับมีดแบบสามช่อง','knife-sharpener']],
 'tableware'=>[['ชุดจานเซรามิก 4 ใบ','ceramic-plates'],['ชุดช้อนส้อมสเตนเลส','cutlery'],['ชามสลัดเซรามิก','ceramic-bowl'],['แก้วน้ำใสทรงสูง 6 ใบ','drinking-glass'],['จานเสิร์ฟทรงรี','serving-plate']],
 'appliances'=>[['เครื่องปั่นอเนกประสงค์','kitchen-blender'],['เครื่องปิ้งขนมปัง 2 ช่อง','toaster'],['กาต้มน้ำไฟฟ้า 1.7 ลิตร','electric-kettle'],['หม้อทอดไร้น้ำมัน 5 ลิตร','air-fryer'],['เครื่องชงกาแฟขนาดกะทัดรัด','coffee-maker']],
 'baking'=>[['พิมพ์เค้กถอดก้น 8 นิ้ว','cake-pan'],['ตะกร้อมือสเตนเลส','whisk'],['ชุดถ้วยตวงและช้อนตวง','measuring-cups'],['พายซิลิโคนทนความร้อน','spatula'],['เครื่องตีแป้งมือถือ','hand-mixer']],
 'food-storage'=>[['กล่องแก้วถนอมอาหาร 3 ใบ','food-container'],['โหลแก้วฝาปิดสุญญากาศ','glass-jar'],['กล่องข้าวแบ่ง 3 ช่อง','lunch-box'],['ชุดกระปุกเก็บเครื่องปรุง','spice-jars'],['ถุงซิลิโคนเก็บอาหาร','food-storage-bag']],
 'cleaning'=>[['แปรงล้างจานด้ามยาว','dish-brush'],['ผ้าไมโครไฟเบอร์ 5 ผืน','microfiber-cloth'],['ที่กดน้ำยาพร้อมฟองน้ำ','soap-dispenser'],['ถุงมือยางทำความสะอาด','rubber-gloves'],['ชุดไม้กวาดและที่ตักผง','broom-dustpan']],
];
$categories=$db->query('SELECT id,name,slug FROM categories ORDER BY id')->fetchAll();$dir=__DIR__.'/../assets/images/products/rorm888';if(!is_dir($dir)&&!mkdir($dir,0755,true)){fwrite(STDERR,"Cannot create image directory\n");exit(3);}
$exists=$db->prepare('SELECT id FROM products WHERE seller_id=? AND name=?');$insert=$db->prepare("INSERT INTO products(category_id,seller_id,name,description,price,stock_quantity,image_url,is_featured,approval_status,admin_note) VALUES(?,?,?,?,?,?,?,0,'approved','สินค้าทดสอบร้าน Rorm888')");$movement=$db->prepare("INSERT INTO inventory_movements(seller_id,product_id,movement_type,quantity_change,quantity_before,quantity_after,note,created_by) VALUES(?,?,'initial',?,0,?,'ข้อมูลทดสอบ',?)");$created=$skipped=0;$lock=8800;
foreach($categories as $category){$items=$catalog[$category['slug']]??[];if(count($items)<5){fwrite(STDERR,"No catalog for {$category['slug']}\n");continue;}foreach(array_slice($items,0,5) as $i=>$item){[$name,$keyword]=$item;$name='Rorm Select '.$name;$exists->execute([$seller['user_id'],$name]);if($exists->fetchColumn()){$skipped++;continue;}$filename=$category['id'].'-'.($i+1).'.jpg';$target=$dir.'/'.$filename;$url='https://loremflickr.com/800/800/'.rawurlencode($keyword).'?lock='.($lock++);$image=@file_get_contents($url);if($image===false||strlen($image)<1000){fwrite(STDERR,"Image download failed: $name\n");continue;}file_put_contents($target,$image);$price=199+((int)$category['id']*170)+($i*125);$stock=12+($i*7);$description='สินค้าทดสอบหมวด'.$category['name'].' สำหรับตรวจสอบหน้าร้าน ตะกร้า สต็อก โปรโมชัน และขั้นตอนสั่งซื้อ';$db->beginTransaction();try{$insert->execute([(int)$category['id'],(int)$seller['user_id'],$name,$description,$price,$stock,'assets/images/products/rorm888/'.$filename]);$id=(int)$db->lastInsertId();$movement->execute([(int)$seller['user_id'],$id,$stock,$stock,(int)$seller['user_id']]);$db->commit();$created++;echo "Created [$id] $name\n";}catch(Throwable $e){$db->rollBack();@unlink($target);throw $e;}}}
echo "Done store={$seller['shop_name']} seller_id={$seller['user_id']} created=$created skipped=$skipped\n";
$verify=$db->prepare("SELECT c.name,COUNT(*) total FROM products p JOIN categories c ON c.id=p.category_id WHERE p.seller_id=? AND p.name LIKE 'Rorm Select %' GROUP BY c.id,c.name ORDER BY c.id");$verify->execute([$seller['user_id']]);foreach($verify as $row)echo "Verify {$row['name']}: {$row['total']} products\n";
