<?php
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';require_once __DIR__.'/../includes/security_monitor.php';
if($_SERVER['REQUEST_METHOD']!=='POST')jsonResponse('error','อนุญาตเฉพาะ POST',[],405);if(!isLoggedIn())jsonResponse('error','กรุณาเข้าสู่ระบบ',[],401);requireCsrf();$db=(new Database())->getConnection();if(!$db)jsonResponse('error','ไม่สามารถเชื่อมต่อฐานข้อมูลได้',[],503);protectApiMutation($db,'api.addresses',30,60);$uid=(int)$_SESSION['user_id'];$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);
if($action==='delete'){$stmt=$db->prepare('DELETE FROM user_addresses WHERE id=? AND user_id=?');$stmt->execute([$id,$uid]);jsonResponse($stmt->rowCount()?'success':'error',$stmt->rowCount()?'ลบที่อยู่แล้ว':'ไม่พบที่อยู่',[],$stmt->rowCount()?200:404);}
if($action==='default'){try{$db->beginTransaction();$exists=$db->prepare('SELECT 1 FROM user_addresses WHERE id=? AND user_id=? FOR UPDATE');$exists->execute([$id,$uid]);if(!$exists->fetchColumn())throw new RuntimeException('ไม่พบที่อยู่');$db->prepare('UPDATE user_addresses SET is_default=0 WHERE user_id=?')->execute([$uid]);$db->prepare('UPDATE user_addresses SET is_default=1 WHERE id=? AND user_id=?')->execute([$id,$uid]);$db->commit();jsonResponse('success','ตั้งเป็นที่อยู่เริ่มต้นแล้ว');}catch(Throwable $e){if($db->inTransaction())$db->rollBack();jsonResponse('error',$e->getMessage(),[],404);}}
if(in_array($action,['save','update'],true)){
 $label=trim((string)($_POST['label']??'บ้าน'));$name=trim((string)($_POST['recipient_name']??''));$phone=trim((string)($_POST['phone']??''));$address=trim((string)($_POST['address_line']??''));
 if($name===''||!preg_match('/^[0-9+ -]{8,20}$/',$phone)||!preg_match('/\b(\d{5})\b/u',$address,$m))jsonResponse('error','กรุณากรอกชื่อ เบอร์โทร และที่อยู่พร้อมรหัสไปรษณีย์ให้ครบ',[],422);
 preg_match('/ตำบล\/แขวง\s+(.+?)\s+อำเภอ\/เขต/u',$address,$sm);preg_match('/อำเภอ\/เขต\s+(.+?)\s+จังหวัด/u',$address,$dm);preg_match('/จังหวัด\s+(.+?)\s+\d{5}\b/u',$address,$pm);if(empty($sm[1])||empty($dm[1])||empty($pm[1]))jsonResponse('error','กรุณาเลือกจังหวัด อำเภอ และตำบลจากตัวเลือก',[],422);
 $values=[mb_substr($label,0,50),$name,$phone,$address,trim($sm[1]),trim($dm[1]),trim($pm[1]),$m[1]];
 if($action==='update'){$stmt=$db->prepare('UPDATE user_addresses SET label=?,recipient_name=?,phone=?,address_line=?,subdistrict=?,district=?,province=?,postal_code=? WHERE id=? AND user_id=?');$stmt->execute([...$values,$id,$uid]);if(!$stmt->rowCount())jsonResponse('error','ไม่พบที่อยู่หรือข้อมูลไม่มีการเปลี่ยนแปลง',[],404);jsonResponse('success','แก้ไขที่อยู่แล้ว');}
 $count=$db->prepare('SELECT COUNT(*) FROM user_addresses WHERE user_id=?');$count->execute([$uid]);$default=(int)$count->fetchColumn()===0?1:0;$stmt=$db->prepare('INSERT INTO user_addresses(user_id,label,recipient_name,phone,address_line,subdistrict,district,province,postal_code,is_default) VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$uid,...$values,$default]);jsonResponse('success','บันทึกที่อยู่แล้ว');
}
jsonResponse('error','คำสั่งไม่ถูกต้อง',[],400);
