<?php
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';require_once __DIR__.'/../includes/security_monitor.php';require_once __DIR__.'/../includes/ai_chat.php';
$db=(new Database())->getConnection();if(!$db)jsonResponse('error','ระบบผู้ช่วยยังไม่พร้อม',[],503);$action=$_GET['action']??$_POST['action']??'history';
function chatConversation(PDO $db):array{$public=$_SESSION['chat_public_id']??'';$conversation=null;if($public){$s=$db->prepare('SELECT * FROM chat_conversations WHERE public_id=? AND (user_id IS NULL OR user_id=?)');$s->execute([$public,(int)($_SESSION['user_id']??0)]);$conversation=$s->fetch();}if(!$conversation){$public=bin2hex(random_bytes(16));$db->prepare('INSERT INTO chat_conversations(public_id,user_id) VALUES(?,?)')->execute([$public,$_SESSION['user_id']??null]);$_SESSION['chat_public_id']=$public;$conversation=['id'=>(int)$db->lastInsertId(),'public_id'=>$public,'status'=>'bot'];}return $conversation;}
$conversation=chatConversation($db);
if($action==='history'){$s=$db->prepare('SELECT sender,message,metadata_json,created_at FROM chat_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 30');$s->execute([(int)$conversation['id']]);$items=array_reverse($s->fetchAll());jsonResponse('success','โหลดบทสนทนาแล้ว',['items'=>$items,'status'=>$conversation['status'],'ai_enabled'=>appConfig('OPENAI_API_KEY','')!=='']);}
if($_SERVER['REQUEST_METHOD']!=='POST')jsonResponse('error','อนุญาตเฉพาะ POST',[],405);requireCsrf();enforceRequestRate($db,'api.chatbot',25,60,$_SESSION['user_id']??null);
if($action==='escalate'){if(!isLoggedIn())jsonResponse('error','กรุณาเข้าสู่ระบบก่อนส่งต่อเจ้าหน้าที่',['login_url'=>BASE_URL.'login.php'],401);$db->beginTransaction();try{$ticketNo='KM'.date('ymd').strtoupper(bin2hex(random_bytes(3)));$db->prepare("INSERT INTO support_tickets(ticket_no,user_id,category,subject,priority,status) VALUES(?,?,'other','ส่งต่อจากผู้ช่วย KitchenMart','normal','waiting_staff')")->execute([$ticketNo,(int)$_SESSION['user_id']]);$ticketId=(int)$db->lastInsertId();$s=$db->prepare('SELECT sender,message FROM chat_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 12');$s->execute([(int)$conversation['id']]);$transcript=implode("\n",array_map(fn($m)=>($m['sender']==='user'?'ลูกค้า':'ผู้ช่วย').': '.$m['message'],array_reverse($s->fetchAll())));$db->prepare('INSERT INTO support_messages(ticket_id,sender_user_id,message,is_staff) VALUES(?,?,?,0)')->execute([$ticketId,(int)$_SESSION['user_id'],mb_substr("ส่งต่อจาก Chatbot\n\n".$transcript,0,5000)]);$db->prepare("UPDATE chat_conversations SET status='waiting_staff' WHERE id=?")->execute([(int)$conversation['id']]);createRoleNotification($db,'admin','support','แชทขอคุยเจ้าหน้าที่ '.$ticketNo,'ลูกค้าส่งต่อบทสนทนาจาก Chatbot',BASE_URL.'admin/support.php?id='.$ticketId);$db->commit();jsonResponse('success','ส่งต่อเจ้าหน้าที่แล้ว',['ticket_no'=>$ticketNo,'url'=>BASE_URL.'support.php?id='.$ticketId]);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();jsonResponse('error','ส่งต่อเจ้าหน้าที่ไม่สำเร็จ',[],500);}}
if($action!=='message')jsonResponse('error','คำสั่งไม่ถูกต้อง',[],400);$message=trim((string)($_POST['message']??''));if(mb_strlen($message)<1||mb_strlen($message)>1000)jsonResponse('error','ข้อความต้องมี 1–1,000 ตัวอักษร',[],422);if(preg_match('/password|รหัสผ่าน|otp|api.?key|เลขบัตร/u',$message))jsonResponse('error','เพื่อความปลอดภัย กรุณาอย่าส่งรหัสผ่าน OTP เลขบัตร หรือ API key ในแชท',[],422);
$db->prepare("INSERT INTO chat_messages(conversation_id,sender,message) VALUES(?,'user',?)")->execute([(int)$conversation['id'],$message]);$context=chatbotContext($db,$message);$s=$db->prepare('SELECT sender,message FROM chat_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 8');$s->execute([(int)$conversation['id']]);$history=array_reverse($s->fetchAll());$answer=chatbotOpenAI($history,$context['text']);$source=$answer?'ai':'local';
if(!$answer){$kb=$db->query('SELECT question,answer,keywords FROM chat_knowledge_base WHERE is_active=1 ORDER BY priority DESC')->fetchAll();$best=null;$score=0;foreach($kb as $item){$current=0;foreach(preg_split('/\s+/u',$item['keywords']) as $word)if($word!==''&&mb_stripos($message,$word)!==false)$current++;if($current>$score){$score=$current;$best=$item;}}if($context['products']){$answer='พบสินค้าที่น่าสนใจ '.count($context['products']).' รายการ เลือกดูจากการ์ดด้านล่างได้เลย';}elseif(preg_match('/คำสั่งซื้อ|ออเดอร์|พัสดุ|ชำระ/u',$message)&&str_contains($context['text'],'คำสั่งซื้อของผู้ใช้')){$orders=array_values(array_filter(explode("\n",$context['text']),fn($line)=>str_starts_with($line,'คำสั่งซื้อของผู้ใช้')));$answer="ข้อมูลล่าสุดของคุณ:\n".implode("\n",$orders);}elseif($best&&$score>0)$answer=$best['answer'];elseif(preg_match('/สวัสดี|หวัดดี|hello|ช่วย/u',$message))$answer='สวัสดีค่ะ ฉันช่วยค้นหาสินค้า แนะนำตามงบ ตรวจคำสั่งซื้อ อธิบายการชำระเงิน คูปอง และการคืนสินค้าได้';else $answer='ฉันยังไม่มีข้อมูลเพียงพอสำหรับคำถามนี้ คุณสามารถกด “คุยกับเจ้าหน้าที่” เพื่อให้ทีมงานช่วยตรวจสอบได้';}
$metadata=['source'=>$source,'products'=>array_map(fn($p)=>['id'=>(int)$p['id'],'name'=>$p['name'],'price'=>(float)$p['price'],'stock'=>(int)$p['stock_quantity'],'image_url'=>productImageUrl($p['image_url']),'url'=>BASE_URL.'product-detail.php?id='.(int)$p['id']],$context['products'])];$db->prepare("INSERT INTO chat_messages(conversation_id,sender,message,metadata_json) VALUES(?,'bot',?,?)")->execute([(int)$conversation['id'],$answer,json_encode($metadata,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$db->prepare('UPDATE chat_conversations SET last_message_at=NOW() WHERE id=?')->execute([(int)$conversation['id']]);jsonResponse('success','ตอบข้อความแล้ว',['message'=>$answer,'metadata'=>$metadata]);
