<?php
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../includes/functions.php';
require_once __DIR__.'/../includes/security_monitor.php';
if($_SERVER['REQUEST_METHOD']!=='POST')jsonResponse('error','อนุญาตเฉพาะ POST',[],405);
$secret=appConfig('PAYMENT_WEBHOOK_SECRET','');if($secret==='')jsonResponse('error','ยังไม่ได้ตั้งค่า Webhook',[],503);
$raw=file_get_contents('php://input')?:'';$signature=strtolower(trim((string)($_SERVER['HTTP_X_KITCHENMART_SIGNATURE']??'')));
if($signature===''||!hash_equals(hash_hmac('sha256',$raw,$secret),$signature))jsonResponse('error','ลายเซ็นไม่ถูกต้อง',[],401);
$event=json_decode($raw,true);if(!is_array($event))jsonResponse('error','Payload ไม่ถูกต้อง',[],400);
$reference=trim((string)($event['reference']??''));$eventId=trim((string)($event['event_id']??''));$occurredAt=(int)($event['occurred_at']??0);$orderNo=trim((string)($event['order_no']??''));$status=(string)($event['status']??'');$amount=(float)($event['amount']??-1);
if($reference===''||$eventId===''||$occurredAt<1||abs(time()-$occurredAt)>600||$orderNo===''||!in_array($status,['paid','failed','expired'],true)||$amount<0)jsonResponse('error','ข้อมูลธุรกรรมไม่ครบหรือหมดอายุ',[],422);
$db=(new Database())->getConnection();if(!$db)jsonResponse('error','ไม่สามารถเชื่อมต่อฐานข้อมูลได้',[],503);
try{
 $db->beginTransaction();
 try{$payloadHash=hash('sha256',$raw);$remember=$db->prepare('INSERT INTO webhook_events(provider,event_id,payload_hash,occurred_at) VALUES(?,?,?,FROM_UNIXTIME(?))');$remember->execute(['kitchenmart',$eventId,$payloadHash,$occurredAt]);}catch(PDOException $duplicate){if((int)($duplicate->errorInfo[1]??0)===1062){$check=$db->prepare('SELECT payload_hash FROM webhook_events WHERE provider=? AND event_id=?');$check->execute(['kitchenmart',$eventId]);$known=(string)$check->fetchColumn();$db->rollBack();if(!hash_equals($known,hash('sha256',$raw))){recordSecurityEvent($db,'webhook.replay_mismatch',80,null,['event_id'=>$eventId],'rejected');jsonResponse('error','Event ID ซ้ำแต่ข้อมูลไม่ตรงกัน',[],409);}jsonResponse('success','รับเหตุการณ์นี้แล้ว');}throw $duplicate;}
 $stmt=$db->prepare("SELECT pt.*,o.order_no,o.user_id,o.total_amount,o.payment_status FROM payment_transactions pt JOIN orders o ON o.id=pt.order_id WHERE o.order_no=? ORDER BY pt.id DESC LIMIT 1 FOR UPDATE");$stmt->execute([$orderNo]);$payment=$stmt->fetch();if(!$payment)throw new RuntimeException('ไม่พบธุรกรรม');if(abs((float)$payment['amount']-$amount)>0.001)throw new RuntimeException('ยอดเงินไม่ตรงกับคำสั่งซื้อ');
 if($payment['status']==='paid'){if($payment['provider_reference']!==$reference)throw new RuntimeException('ธุรกรรมนี้ชำระแล้วด้วยหมายเลขอ้างอิงอื่น');$db->prepare('UPDATE webhook_events SET processed_at=NOW() WHERE provider=? AND event_id=?')->execute(['kitchenmart',$eventId]);$db->commit();jsonResponse('success','รับเหตุการณ์นี้แล้ว');}
 $db->prepare('UPDATE payment_transactions SET provider_reference=?,status=?,payload_json=?,paid_at=IF(?="paid",NOW(),NULL) WHERE id=?')->execute([$reference,$status,$raw,$status,(int)$payment['id']]);$db->prepare('UPDATE orders SET payment_status=? WHERE id=?')->execute([$status,(int)$payment['order_id']]);auditLog($db,'payment.webhook.'.$status,'payment_transaction',(int)$payment['id'],null,['reference'=>$reference,'event_id'=>$eventId,'amount'=>$amount]);if($status==='paid')createNotification($db,(int)$payment['user_id'],'payment','ยืนยันการชำระเงินแล้ว','คำสั่งซื้อ '.$orderNo.' ชำระเงินสำเร็จ',BASE_URL.'order-detail.php?id='.(int)$payment['order_id']);$db->prepare('UPDATE webhook_events SET processed_at=NOW() WHERE provider=? AND event_id=?')->execute(['kitchenmart',$eventId]);$db->commit();jsonResponse('success','บันทึกสถานะการชำระเงินแล้ว');
}catch(RuntimeException $e){if($db->inTransaction())$db->rollBack();jsonResponse('error',$e->getMessage(),[],409);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();jsonResponse('error','ประมวลผล Webhook ไม่สำเร็จ',[],500);}
